SELECT 
       ACCOUNTNUMBER,
       REPLACE(REPLACE(A.ACCOUNT_EXTID,CHR (10),' '),CHR (13),' ') AS ACCOUNT_EXTID,
       TO_CHAR(A.ACCOUNT_ID) AS ACCOUNT_ID,
       REPLACE(REPLACE(A.ACCPAC_CODES,CHR (10),' '),CHR (13),' ') AS ACCPAC_CODES,
       REPLACE(REPLACE(A.BANK_ACCOUNT_NUMBER,CHR (10),' '),CHR (13),' ') AS BANK_ACCOUNT_NUMBER,
       CASHFLOW_RATE_TYPE,
       CATEGORY_1099_MISC,
       CATEGORY_1099_MISC_MTHRESHOLD,
       TO_CHAR(A.CLASS_ID) AS CLASS_ID,
       F.NAME AS LINE_OF_BUSINESS,
       TO_CHAR(A.CURRENCY_ID) AS CURRENCY_ID,
       C.NAME AS CURRENCY_NAME,
       TO_CHAR(A.DATE_LAST_MODIFIED,'YYYY-MM-DD HH24:MI:SS') AS DATE_LAST_MODIFIED,
       TO_CHAR(A.DEFERRAL_ACCOUNT_ID) AS DEFERRAL_ACCOUNT_ID,
       TO_CHAR(A.DEPARTMENT_ID) AS DEPARTMENT_ID,
       H.NAME AS COST_CENTER_NAME,
       DESCRIPTION,
       FULL_DESCRIPTION,
       REPLACE(REPLACE(A.FULL_NAME,CHR (10),' '),CHR (13),' ') AS FULL_NAME,
       GENERAL_RATE_TYPE,
       REPLACE(REPLACE(A.HYPERION_CODES,CHR (10),' '),CHR (13),' ') AS HYPERION_CODES,
       ISINACTIVE,
       IS_BALANCESHEET,
       IS_INCLUDED_IN_ELIMINATION,
       IS_INCLUDED_IN_REVAL,
       IS_LEFTSIDE,
       IS_SUMMARY,
       TO_CHAR(A.LOCATION_ID) AS LOCATION_ID,
       G.NAME AS LOCATION_NAME,
       NAME,
       TO_CHAR(OPENBALANCE) AS OPENBALANCE,
       TO_CHAR(A.PARENT_ID) AS PARENT_ID,
       B.FULL_NAME AS PARENT_ACCOUNT_NAME,
       B.ACCOUNTNUMBER AS PARENT_ACCOUNT_NUMBER,
       TYPE_NAME,
       TYPE_SEQUENCE
FROM ACCOUNTS A
  LEFT OUTER JOIN ACCOUNTS B ON (A.PARENT_ID = B.ACCOUNT_ID)
  LEFT OUTER JOIN CURRENCIES C ON (A.CURRENCY_ID = C.CURRENCY_ID)
  LEFT OUTER JOIN CLASSES F ON (A.CLASS_ID = F.CLASS_ID)
  LEFT OUTER JOIN LOCATIONS G ON (A.LOCATION_ID = G.LOCATION_ID)
  LEFT OUTER JOIN DEPARTMENTS H ON (A.DEPARTMENT_ID = H.DEPARTMENT_ID)
WHERE A.DATE_LAST_MODIFIED >= '1900-01-01 00:00:00'

