CREATE SCHEMA if not exists dw;

DROP TABLE if exists dw.carrier;

CREATE TABLE dw.carrier 
(
  CARRIER_KEY        INTEGER,
  CARRIER_ID         INTEGER,
  CARRIER_NAME       VARCHAR(200),
  CARRIER_ADDRESS    VARCHAR(4000),
  DATE_ACTIVE_FROM   TIMESTAMP,
  DATE_ACTIVE_TO     TIMESTAMP,
  DW_ACTIVE          VARCHAR(1),
  PRIMARY KEY (CARRIER_KEY,CARRIER_ID)
)
DISTSTYLE ALL COMPOUND SORTKEY (CARRIER_KEY,CARRIER_ID,DW_ACTIVE);

