SELECT
REPLACE(REPLACE(CARRIER_RECORD.CARRIER_ADDRESS,CHR(10),' '),CHR(13),' ') AS CARRIER_ADDRESS , 
TO_CHAR(CARRIER_RECORD.CARRIER_RECORD_ID) AS CARRIER_RECORD_ID , 
REPLACE(REPLACE(CARRIER_RECORD.CARRIER_RECORD_NAME,CHR(10),' '),CHR(13),' ') AS CARRIER_RECORD_NAME , 
TO_CHAR(CARRIER_RECORD.DATE_CREATED,'YYYY-MM-DD HH24:MI:SS') AS DATE_CREATED , 
IS_INACTIVE , 
TO_CHAR(CARRIER_RECORD.LAST_MODIFIED_DATE,'YYYY-MM-DD HH24:MI:SS') AS LAST_MODIFIED_DATE 
FROM
CARRIER_RECORD
WHERE DATE_LAST_MODIFIED >= '1900-01-01 00:00:00';
 