SELECT
  TO_CHAR(AMORTIZATION__PER_ISSUELEVE_ID) AS AMORTIZATION_PER_ISSUELEVE_ID
  ,AMORTIZE_VALUE_PER_ISSUE_EXCL          
  ,AMORTIZE_VALUE_PER_ISSUE_INCL  
  ,TO_CHAR(COMPONENTS_ID) AS COMPONENTS_ID                   
  ,DATE_CREATED
  ,DISCOUNTED_AMOUNT       
  ,DISCOUNTED_PRICE        
  ,IS_INACTIVE             
  ,LAST_MODIFIED_DATE      
  ,LAST_SS_YYYYMM          
  ,TO_CHAR(LEVEL_ID)   LEVEL_ID  
  ,CLUBLEVELREADING_LEVEL_NAME LEVEL
  ,LINE_NO                         
  ,NO_OF_ISSUES                    
  ,NO_OF_SCHEDULED_CREATED_TILL_ NO_OF_SCHEDULED_CREATED         
  ,TO_CHAR(ORDER_TYPE_ID)  ORDER_TYPE_ID
  ,C.LIST_ITEM_NAME ORDER_TYPE                 
  ,RRP                  
  ,STO_END_DATE 
  ,TO_CHAR(STO_ITEM_ID) STO_ITEM_ID  
  ,TO_CHAR(STO_NO_ID) STO_NO_ID 
  ,TO_CHAR(E.SUBSIDIARY_ID) SUBSIDIARY_ID
  ,STO_START_DATE   
  FROM
 AMORTIZATION__PER_ISSUELEVEL A
 LEFT OUTER JOIN CLUBLEVELREADING_LEVEL B ON (A.LEVEL_ID = B.CLUBLEVELREADING_LEVEL_ID )
 LEFT OUTER JOIN ORDER_TYPE C ON (A.ORDER_TYPE_ID = C.LIST_ID) 
 LEFT OUTER JOIN TRANSACTIONS D ON (A.STO_NO_ID = D.TRANSACTION_ID)
 LEFT OUTER JOIN TRANSACTION_LINES E ON (D.TRANSACTION_ID = E.TRANSACTION_ID)
 LEFT OUTER JOIN ACCOUNTS F ON (E.ACCOUNT_ID = F.ACCOUNT_ID)
WHERE E.SUBSIDIARY_ID = '%s'
AND A.LAST_MODIFIED_DATE >= to_timestamp('%s','YYYY-MM-DD HH24:MI:SS')
AND F.NAME = 'Sales Orders'
AND D.TRANSACTION_TYPE = 'Sales Order'
AND E.TRANSACTION_LINE_ID = 0
ORDER BY AMORTIZATION__PER_ISSUELEVE_ID,E.SUBSIDIARY_ID,STO_ITEM_ID,STO_START_DATE