CREATE SCHEMA if not exists dw;

DROP TABLE if exists dw.standing_order_schedule_fact;

CREATE TABLE dw.standing_order_schedule_fact 
(
  STANDING_ORDER_SCHEDULE_KEY   BIGINT IDENTITY(0,1),
  STANDING_ORDER_SCHEDULE_ID    INTEGER,
  ACTUAL_SHIPMENT_DATE_KEY      INTEGER,
  AMORTIZATION_VALUE_EXCL_GST   DECIMAL(22,8),
  AMORTIZATION_VALUE_INCL_GST   DECIMAL(22,8),
  CUSTOMER_KEY                  INTEGER,
  EXPECTED_SHIPMENT_DATE_KEY    INTEGER,
  INVOICE_AMOUNT                DECIMAL(22,2),
  INVOICE_NO_ID                 INTEGER,
  IS_INACTIVE                   VARCHAR(10),
  LINE_NO                       DECIMAL(22,0),
  ORDER_TYPE                    VARCHAR(1000),
  PICK_SLIP_NUMBER              DECIMAL(22,0),
  PRODUCT_CATALOGUE_KEY         INTEGER,
  SALES_ORDER_NO_ID             INTEGER,
  SCHEDULE_CLOSED               VARCHAR(10),
  SHIPMENT_NO                  DECIMAL(22,0),
  SHIPMENT_YYYYMM               VARCHAR(4000),
  STO_ITEM_KEY                  INTEGER,
  STO_NO_TEXT                   VARCHAR(4000),
  STO_NO_ID                     INTEGER,
  SUBSIDIARY_KEY                INTEGER,
  STO_START_DATE_KEY            INTEGER,
  STO_END_DATE_KEY              INTEGER,
  LEVEL_KEY                     INTEGER,
  DATE_ACTIVE_FROM              DATE,
  DATE_ACTIVE_TO                DATE,
  DW_CURRENT                    INTEGER,
  PRIMARY KEY (STANDING_ORDER_SCHEDULE_KEY),
  FOREIGN KEY(ACTUAL_SHIPMENT_DATE_KEY) REFERENCES DW.DWDATE (DATE_KEY),
  FOREIGN KEY(EXPECTED_SHIPMENT_DATE_KEY) REFERENCES DW.DWDATE (DATE_KEY),
  FOREIGN KEY(CUSTOMER_KEY) REFERENCES DW.CUSTOMERS (CUSTOMER_KEY),
  FOREIGN KEY(PRODUCT_CATALOGUE_KEY) REFERENCES DW.PRODUCT_CATALOGUE (PRODUCT_CATALOGUE_KEY),
  FOREIGN KEY(STO_ITEM_KEY) REFERENCES DW.ITEMS (ITEM_KEY),
  FOREIGN KEY(SUBSIDIARY_KEY) REFERENCES DW.SUBSIDIARIES  (SUBSIDIARY_KEY),
  FOREIGN KEY(STO_START_DATE_KEY) REFERENCES DW.DWDATE (DATE_KEY),
  FOREIGN KEY(STO_END_DATE_KEY) REFERENCES DW.DWDATE (DATE_KEY),
  FOREIGN KEY(LEVEL_KEY) REFERENCES DW.ITEMS (ITEM_KEY)
)
DISTKEY (PRODUCT_CATALOGUE_KEY) INTERLEAVED SORTKEY (SUBSIDIARY_KEY,CUSTOMER_KEY,PRODUCT_CATALOGUE_KEY,DW_CURRENT);

