CREATE SCHEMA if not exists dw;

DROP TABLE if exists dw.custom_form;

CREATE TABLE dw.custom_form
(
  CUSTOM_FORM_KEY         BIGINT IDENTITY(0,1),
  CUSTOM_FORM_ID          INTEGER,
  CUSTOM_FORM_NAME        VARCHAR(1000),
  FORM_TYPE               VARCHAR(100),
  DATE_ACTIVE_FROM        TIMESTAMP,
  DATE_ACTIVE_TO          TIMESTAMP,
  DW_ACTIVE               VARCHAR(1),
  PRIMARY KEY (CUSTOM_FORM_KEY,CUSTOM_FORM_ID)
)
DISTSTYLE ALL INTERLEAVED SORTKEY (CUSTOM_FORM_KEY,CUSTOM_FORM_ID,DW_ACTIVE);

INSERT INTO dw.custom_form
(
  CUSTOM_FORM_ID,          
  CUSTOM_FORM_NAME,
  FORM_TYPE,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE
)
SELECT -99 AS CUSTOM_FORM_ID,
       'NA_GDW' AS CUSTOM_FORM_NAME,
       'NA_GDW' AS FORM_TYPE,
        SYSDATE AS DATE_ACTIVE_FROM,
       '9999-12-31 23:59:59' AS DATE_ACTIVE_TO,
       'A' AS dw_active;

INSERT INTO dw.classes
(
  CUSTOM_FORM_ID,          
  CUSTOM_FORM_NAME,
  FORM_TYPE,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE
)
SELECT  0 AS CUSTOM_FORM_ID,
       'NA_ERR' AS CUSTOM_FORM_NAME,
       'NA_ERR' AS FORM_TYPE,
        SYSDATE AS DATE_ACTIVE_FROM,
       '9999-12-31 23:59:59' AS DATE_ACTIVE_TO,
       'A' AS dw_active;