SELECT B.TRANID AS DOCUMENT_NUMBER,
       B.TRANSACTION_NUMBER AS TRANSACTION_NUMBER,
       TO_CHAR(A.TRANSACTION_ID) AS TRANSACTION_ID,
       TO_CHAR(A.TRANSACTION_LINE_ID) AS TRANSACTION_LINE_ID,
       TO_CHAR(A.TRANSACTION_ORDER) AS TRANSACTION_ORDER,
       F.TRANSACTION_NUMBER AS REF_DOC_NUMBER,
       TO_CHAR(F.CUSTOM_FORM_ID) AS REF_CUSTOM_FORM_ID,
       TO_CHAR(B.PAYMENT_TERMS_ID) AS PAYMENT_TERMS_ID,
       B.REVENUE_COMMITMENT_STATUS,
       B.REVENUE_STATUS,
       TO_CHAR(NVL(B.SALES_REP_ID,H.SALES_REP_ID)) AS SALES_REP_ID,
       TO_CHAR(B.SALES_TERRITORY_ID) AS SALES_TERRITORY_ID,
       E.BILL_ADDRESS_LINE_1,
       E.BILL_ADDRESS_LINE_2,
       E.BILL_ADDRESS_LINE_3,
       E.BILL_CITY,
       E.BILL_COUNTRY,
       E.BILL_STATE,
       E.BILL_ZIP,
       E.SHIP_ADDRESS_LINE_1,
       E.SHIP_ADDRESS_LINE_2,
       E.SHIP_ADDRESS_LINE_3,
       E.SHIP_CITY,
       E.SHIP_COUNTRY,
       E.SHIP_STATE,
       E.SHIP_ZIP,
       B.STATUS ,
       B.TRANSACTION_TYPE AS TRANSACTION_TYPE,
       TO_CHAR(B.CURRENCY_ID) AS CURRENCY_ID,
       TO_CHAR(B.TRANDATE,'YYYY-MM-DD HH24:MI:SS') AS TRANDATE,
       B.EXCHANGE_RATE,
       TO_CHAR(A.ACCOUNT_ID) AS ACCOUNT_ID,
       TO_CHAR(A.AMOUNT) AS AMOUNT,
       TO_CHAR(A.AMOUNT_FOREIGN) AS AMOUNT_FOREIGN,
       TO_CHAR(A.GROSS_AMOUNT) AS GROSS_AMOUNT,
       TO_CHAR(A.NET_AMOUNT) AS NET_AMOUNT,
       TO_CHAR(A.NET_AMOUNT_FOREIGN) AS NET_AMOUNT_FOREIGN,
       TO_CHAR(A.RRP) AS RRP,
       TO_CHAR(J.AVERAGE_COST) AS AVG_COST,
       TO_CHAR(A.ITEM_COUNT) AS QUANTITY,
       TO_CHAR(A.QUANTITY_COMMITTED) AS COMMITTED_QUANTITY,
       TO_CHAR(A.ITEM_ID) AS ITEM_ID,
       B.REWARDS_EARN,
	   B.REWARD_BALANCE,
       TO_CHAR(A.ITEM_UNIT_PRICE) AS ITEM_UNIT_PRICE,
       TO_CHAR(A.TAX_ITEM_ID) AS TAX_ITEM_ID,
       TO_CHAR(D.AMOUNT) AS TAX_AMOUNT,
       TO_CHAR(B.LOCATION_ID) AS LOCATION_ID,
       TO_CHAR(A.CLASS_ID) AS CLASS_ID,
       TO_CHAR(A.SUBSIDIARY_ID) AS SUBSIDIARY_ID,
       TO_CHAR(B.ACCOUNTING_PERIOD_ID) AS ACCOUNTING_PERIOD_ID,
       TO_CHAR(B.ENTITY_ID) AS CUSTOMER_ID,
       TO_CHAR(A.PRICE_TYPE_ID) AS PRICE_TYPE_ID,
	   L.NAME PRICE_TYPE,
       TO_CHAR(B.CUSTOM_FORM_ID) AS CUSTOM_FORM_ID,
       TO_CHAR(B.CREATED_BY_ID) AS CREATED_BY_ID,
       TO_CHAR(B.OFFER_ID) AS OFFER_ID,
       TO_CHAR(A.PRODUCT_CATALOGUE_ID) AS  PRODUCT_CATALOGUE_ID,
       TO_CHAR(A.BROCHURE_CODE) AS BROCHURE_CODE,
       TO_CHAR(A.TEACHER_ID) AS TEACHER_ID,
       TO_CHAR(BOOK_FAIRS_CONSULTANT_ID) AS BOOK_FAIRS_CONSULTANT_ID,
	   K.LIST_ITEM_NAME NEXT_ACTION,
       TO_CHAR(B.CREATE_DATE,'YYYY-MM-DD HH24:MI:SS') AS CREATE_DATE,
       TO_CHAR(A.DATE_LAST_MODIFIED,'YYYY-MM-DD HH24:MI:SS') AS DATE_LAST_MODIFIED,
       DECODE(c.name,
             'Sales Orders','SO_HDR',
             decode(a.transaction_line_id,0,'SO_HDR',decode(d.transaction_line_id,NULL,decode(i.item_id,NULL,'SO_LINE','SO_TAX'),'SO_LINE'))
       ) AS trx_type,
	  NULL prepack_id
FROM TRANSACTION_LINES A
  INNER JOIN TRANSACTIONS B ON (TRANSACTION_LINES.TRANSACTION_ID = TRANSACTIONS.TRANSACTION_ID)
  LEFT OUTER JOIN ACCOUNTS C ON (TRANSACTION_LINES.ACCOUNT_ID = ACCOUNTS.ACCOUNT_ID)
  LEFT OUTER JOIN TRANSACTION_TAX_DETAIL D
               ON (TRANSACTION_LINES.TRANSACTION_ID = TRANSACTION_TAX_DETAIL.TRANSACTION_ID
              AND TRANSACTION_LINES.TRANSACTION_LINE_ID = TRANSACTION_TAX_DETAIL.TRANSACTION_LINE_ID)
  LEFT OUTER JOIN TRANSACTION_ADDRESS E ON (TRANSACTION_LINES.TRANSACTION_ID = TRANSACTION_ADDRESS.TRANSACTION_ID)
  LEFT OUTER JOIN TRANSACTIONS F ON (B.CREATED_FROM_ID = F.TRANSACTION_ID)
  LEFT OUTER JOIN CUSTOMERS H ON (B.ENTITY_ID = H.CUSTOMER_ID)
  LEFT OUTER JOIN TAX_ITEMS I ON (A.ITEM_ID = I.ITEM_ID)
  LEFT OUTER JOIN ITEM_LOCATION_MAP J ON (A.ITEM_ID = J.ITEM_ID AND A.LOCATION_ID = J.LOCATION_ID)
  LEFT OUTER JOIN BC_NEXT_ACTION K ON (A.NEXT_ACTION_TAKEN_ID = K.LIST_ID )
  LEFT OUTER JOIN PRICE_TYPES L ON (A.PRICE_TYPE_ID = L.PRICE_TYPE_ID )
WHERE A.SUBSIDIARY_ID = '%s'
AND   b.transaction_type = 'Sales Order'
AND EXISTS (SELECT 1
              FROM transactions i
              WHERE i.transaction_id = a.transaction_id
              AND   i.transaction_type = 'Sales Order'
	      AND i.date_last_modified >= to_timestamp('%s','YYYY-MM-DD HH24:MI:SS'));