CREATE SCHEMA if not exists dw;

DROP TABLE if exists dw.tax_items;

CREATE TABLE dw.tax_items 
(
  TAX_ITEM_KEY            BIGINT IDENTITY(0,1),
  ITEM_ID                 INTEGER,
  NAME                    VARCHAR(83),
  FULL_NAME               VARCHAR(1800),
  DESCRIPTION             VARCHAR(4000),
  INCOME_ACCOUNT_ID       VARCHAR(4000),
  INCOME_ACCOUNT_NUMBER   VARCHAR(100),
  INCOME_ACCOUNT_NAME     VARCHAR(2000),
  ISINACTIVE              VARCHAR(10),
  RATE                    VARCHAR(500),
  DATE_ACTIVE_FROM        TIMESTAMP,
  DATE_ACTIVE_TO          TIMESTAMP,
  DW_ACTIVE               VARCHAR(1),                       
  PRIMARY KEY (TAX_ITEM_KEY,ITEM_ID,NAME)
)
DISTSTYLE ALL INTERLEAVED SORTKEY (TAX_ITEM_KEY,ITEM_ID,NAME,DW_ACTIVE);

INSERT INTO dw.tax_items
(
  ITEM_ID,
  NAME,
  FULL_NAME,
  DESCRIPTION,
  INCOME_ACCOUNT_ID,
  INCOME_ACCOUNT_NUMBER,
  INCOME_ACCOUNT_NAME,
  ISINACTIVE,
  RATE,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE
)
SELECT -99 AS ITEM_ID,
       'NA_GDW' AS NAME,
       'NA_GDW' AS FULL_NAME,
       'NA_GDW' AS DESCRIPTION,
       'NA_GDW' AS INCOME_ACCOUNT_ID,
       'NA_GDW' AS INCOME_ACCOUNT_NUMBER,
       'NA_GDW' AS INCOME_ACCOUNT_NAME,
       'NA_GDW' AS ISINACTIVE,
       '0' AS RATE,
       sysdate AS DATE_ACTIVE_FROM,
       '9999-12-31 23:59:59' AS DATE_ACTIVE_TO,
       'A' AS DW_ACTIVE;

INSERT INTO dw.tax_items
(
  ITEM_ID,
  NAME,
  FULL_NAME,
  DESCRIPTION,
  INCOME_ACCOUNT_ID,
  INCOME_ACCOUNT_NUMBER,
  INCOME_ACCOUNT_NAME,
  ISINACTIVE,
  RATE,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE
)
SELECT 0 AS ITEM_ID,
       'NA_ERR' AS NAME,
       'NA_ERR' AS FULL_NAME,
       'NA_ERR' AS DESCRIPTION,
       'NA_ERR' AS INCOME_ACCOUNT_ID,
       'NA_ERR' AS INCOME_ACCOUNT_NUMBER,
       'NA_ERR' AS INCOME_ACCOUNT_NAME,
       'NA_ERR' AS ISINACTIVE,
       '0' AS RATE,
       sysdate AS DATE_ACTIVE_FROM,
       '9999-12-31 23:59:59' AS DATE_ACTIVE_TO,
       'A' AS DW_ACTIVE;

COMMIT;

