create schema if not exists dw_prestage ;

drop table if exists dw_prestage.tax_items;

CREATE TABLE dw_prestage.tax_items 
(
  RUNID                  INTEGER,
  ACCOUNT_CLASSIFICATION_ROYA_ID   INTEGER,
  APPLY_FRIEGHT                    VARCHAR(1),
  AUTHORPUBLISHER                  VARCHAR(4000),
  BACKORDERABLE                    VARCHAR(1),
  CARTON_DEPTH                     VARCHAR(4000),
  CARTON_HEIGHT                    DECIMAL(22,8),
  CARTON_QUANTITY                  DECIMAL(22,8),
  CARTON_WEIGHT                    VARCHAR(4000),
  CARTON_WIDTH                     VARCHAR(4000),
  CATALOGUE_USE_ID                 INTEGER,
  COC_TEST_REPORT_REQUIRED         VARCHAR(1),
  COMMODITY_CODE                   VARCHAR(8),
  DATE_LAST_MODIFIED               TIMESTAMP,
  DEFAULT_WT_CODE_ID               INTEGER,
  DESCRIPTION                      VARCHAR(4000),
  FULL_NAME                        VARCHAR(600),
  INCOME_ACCOUNT_ID                INTEGER,
  ISBN10                           VARCHAR(4000),
  ISBN_ANZ_ID                      INTEGER,
  ISINACTIVE                       VARCHAR(3),
  ITEM_EXTID                       VARCHAR(255),
  ITEM_ID                          INTEGER,
  ITEM_JDE_CODE_ID                 INTEGER,
  ITEM_TYPE_ID                     INTEGER,
  LAUNCH_DATE                      TIMESTAMP,
  LEVEL_ID                         INTEGER,
  LEXILE                           DECIMAL(22,8),
  NAME                             VARCHAR(180),
  NATURE_OF_TRANSACTION_CODES_ID   INTEGER,
  NO__OF_ISSUES                    DECIMAL(22,0),
  PAGE_COUNT                       DECIMAL(22,8),
  PALM_ISBN                        VARCHAR(4000),
  PARENT_ID                        INTEGER,
  PLANNERBUYER_NUMBER_ID           INTEGER,
  PLANNER_ID                       INTEGER,
  PRODUCT_CATEGORY_ID              INTEGER,
  PRODUCT_CLASSIFICATION_ID        INTEGER,
  PRODUCT_SERIESFAMILY_ID          INTEGER,
  PRODUCT_TYPE_ANZ_ID              INTEGER,
  PRODUCT_TYPE_ID                  INTEGER,
  PUBLISHER_ID                     INTEGER,
  RATE                             VARCHAR(42),
  ROYALTY_MARKER                   VARCHAR(1),
  SEIS_LAUNCH_DATE                 TIMESTAMP,
  SEIS_PRODUCT_CATEGORY_ID         INTEGER,
  SEIS_PRODUCT_SERIESFAMILY_ID     INTEGER,
  SEIS_PRODUCT_TYPE_ID             INTEGER,
  SELLING_RIGHTS_ID                INTEGER,
  SERIAL_MARKER_ID                 INTEGER,
  SERIAL_NUMBER                    VARCHAR(4000),
  SOR_TAG                          VARCHAR(1),
  SYNC_TO_WMS_ID                   INTEGER,
  TAX_CITY                         VARCHAR(4000),
  TAX_COUNTY                       VARCHAR(41),
  TAX_STATE                        VARCHAR(2),
  TAX_ZIPCODE                      VARCHAR(4000),
  TRADE_RELEASE_DATE_1             TIMESTAMP,
  TRADE_RELEASE_DATE_2             TIMESTAMP,
  UOM_ID                           INTEGER,
  US_ISBN                          VARCHAR(4000),
  VENDORNAME                       VARCHAR(60),
  VENDOR_ID                        INTEGER,
  WANG_ITEM_CODE                   VARCHAR(4000),
  WEIGHT                           VARCHAR(4000),
  WEIGHT_KG                        DECIMAL(22,8),
  INCOME_ACCOUNT_NUMBER            VARCHAR(100),
  INCOME_ACCOUNT_NAME              VARCHAR(2000)
);
