CREATE SCHEMA if not exists dw;

DROP TABLE if exists dw.budgetforecast_fact_error;

CREATE TABLE dw.budgetforecast_fact_error 
(
  RUNID                      BIGINT,
  BUDGETFORECAST_ERROR_KEY   BIGINT IDENTITY(0,1),
  BUDGETFORECAST_ID          INTEGER,
  BUDGETFORECAST_NAME        VARCHAR(2000),
  FISCAL_MONTH_ID            INTEGER,
  FISCAL_WEEK_ID             INTEGER,
  CLASS_KEY                  INTEGER,
  CLASS_ID                   INTEGER, 
  CLASS_ID_ERROR             VARCHAR(100),         
  TERRITORY_KEY              INTEGER,
  TERRITORY_ID               INTEGER,
  TERRITORY_ID_ERROR         VARCHAR(100),         
  SUBSIDIARY_KEY             INTEGER,
  SUBSIDIARY_ID              INTEGER,
  SUBSIDIARY_ID_ERROR        VARCHAR(100),         
  BUDGETFORECAST_TYPE        VARCHAR(500),
  MONTH_END_DATE             TIMESTAMP,
  MONTH_START_DATE           TIMESTAMP,
  WEEK_START_DATE            TIMESTAMP,
  WEEK_END_DATE              TIMESTAMP,
  AMOUNT                     DECIMAL(22,2),
  IS_INACTIVE                VARCHAR(10),
  CREATION_DATE              TIMESTAMP,
  LAST_MODIFIED_DATE         TIMESTAMP,
  RECORD_STATUS              VARCHAR,
  DW_CREATION_DATE           TIMESTAMP,
  PRIMARY KEY (BUDGETFORECAST_ERROR_KEY)
)
DISTKEY(FISCAL_WEEK_ID) INTERLEAVED SORTKEY (BUDGETFORECAST_ERROR_KEY,BUDGETFORECAST_TYPE,BUDGETFORECAST_ID,BUDGETFORECAST_NAME,FISCAL_MONTH_ID,FISCAL_WEEK_ID);

