SELECT
ALLOW_DROP_SHIP , 
APPLY_FRIEGHT , 
TO_CHAR(A.ASSET_ACCOUNT_ID) AS ASSET_ACCOUNT_ID , 
E.ACCOUNTNUMBER||' '||E.FULL_NAME AS ASSET_ACCOUNT_NUMBER,
REPLACE(REPLACE(A.ATP_METHOD,CHR(10),' '),CHR(13),' ') AS ATP_METHOD , 
AVAILABLE_TO_PARTNERS , 
BACKORDERABLE , 
TO_CHAR(A.BILL_EXCH_RATE_VAR_ACCOUNT_ID) AS BILL_EXCH_RATE_VAR_ACCOUNT_ID , 
F.ACCOUNTNUMBER||' '||F.FULL_NAME AS BILL_EXCH_RATE_VAR_ACCOUNT_NUMBER,
TO_CHAR(A.BILL_PRICE_VARIANCE_ACCOUNT_ID) AS BILL_PRICE_VARIANCE_ACCOUNT_ID , 
G.ACCOUNTNUMBER||' '||G.FULL_NAME AS BILL_PRICE_VARIANCE_ACCOUNT_NUMBER,
TO_CHAR(A.BILL_QTY_VARIANCE_ACCOUNT_ID) AS BILL_QTY_VARIANCE_ACCOUNT_ID , 
H.ACCOUNTNUMBER||' '||H.FULL_NAME AS BILL_QTY_VARIANCE_ACCOUNT_NUMBER,
REPLACE(REPLACE(A.CARTON_DEPTH,CHR(10),' '),CHR(13),' ') AS CARTON_DEPTH , 
CARTON_HEIGHT , 
CARTON_QUANTITY , 
REPLACE(REPLACE(A.CARTON_WIDTH,CHR(10),' '),CHR(13),' ') AS CARTON_WIDTH , 
TO_CHAR(A.CLASS_ID) AS CLASS_ID , 
I.NAME AS LINE_OF_BUSINESS,
COSTING_METHOD , 
TO_CHAR(A.CREATED,'YYYY-MM-DD HH24:MI:SS') AS CREATED , 
TO_CHAR(A.DATE_LAST_MODIFIED,'YYYY-MM-DD HH24:MI:SS') AS DATE_LAST_MODIFIED , 
TO_CHAR(A.DEPARTMENT_ID) AS DEPARTMENT_ID , 
J.NAME AS COST_CENTER,
REPLACE(REPLACE(A.DISPLAYNAME,CHR(10),' '),CHR(13),' ') AS DISPLAYNAME , 
TO_CHAR(A.EXPENSE_ACCOUNT_ID) AS EXPENSE_ACCOUNT_ID , 
K.ACCOUNTNUMBER||' '||K.FULL_NAME AS EXPENSE_ACCOUNT_NUMBER,
FEATUREDITEM , 
REPLACE(REPLACE(A.FULL_NAME,CHR(10),' '),CHR(13),' ') AS FULL_NAME , 
TO_CHAR(A.INCOME_ACCOUNT_ID) AS INCOME_ACCOUNT_ID , 
L.ACCOUNTNUMBER||' '||L.FULL_NAME AS INCOME_ACCOUNT_NUMBER,
REPLACE(REPLACE(A.ISBN10,CHR(10),' '),CHR(13),' ') AS ISBN10 , 
TO_CHAR(A.ISBN_ID) AS ISBN_ANZ_ID ,
M.ISBN_NAME ,  
ISINACTIVE , 
REPLACE(REPLACE(A.ITEM_EXTID,CHR(10),' '),CHR(13),' ') AS ITEM_EXTID , 
TO_CHAR(A.ITEM_ID) AS ITEM_ID ,
REPLACE(REPLACE(A.JDE_ITEM_CODE,CHR(10),' '),CHR(13),' ') AS JDE_ITEM_CODE ,
TO_CHAR(A.ITEM_TYPE_ID) AS ITEM_TYPE_ID , 
TO_CHAR(A.LOCATION_ID) AS LOCATION_ID , 
X.NAME AS LOCATIONS,
REPLACE(REPLACE(A.NAME,CHR(10),' '),CHR(13),' ') AS NAME , 
TO_CHAR(A.PARENT_ID) AS PARENT_ID , 
O.NAME AS PARENT_NAME,
TO_CHAR(A.PRODUCT_CATEGORY_ID) AS PRODUCT_CATEGORY_ID , 
TO_CHAR(A.PRODUCT_CLASSIFICATION_ID) AS PRODUCT_CLASSIFICATION_ID , 
TO_CHAR(A.PRODUCT_SERIESFAMILY_ID) AS PRODUCT_SERIESFAMILY_ID , 
TO_CHAR(A.PRODUCT_TYPE_ANZ_ID) AS PRODUCT_TYPE_ANZ_ID , 
TO_CHAR(A.PRODUCT_TYPE_ID) AS PRODUCT_TYPE_ID , 
TO_CHAR(A.PROD_PRICE_VAR_ACCOUNT_ID) AS PROD_PRICE_VAR_ACCOUNT_ID , 
P.ACCOUNTNUMBER||' '||P.FULL_NAME AS PROD_PRICE_VAR_ACCOUNT_NUMBER,
TO_CHAR(A.PROD_QTY_VAR_ACCOUNT_ID) AS PROD_QTY_VAR_ACCOUNT_ID , 
Q.ACCOUNTNUMBER||' '||Q.FULL_NAME AS PROD_QTY_VAR_ACCOUNT_NUMBER,
TO_CHAR(A.PUBLISHER_ID) AS PUBLISHER_ID , 
TO_CHAR(A.SELLING_RIGHTS_ID) AS SELLING_RIGHTS_ID , 
REPLACE(REPLACE(A.SERIAL_NUMBER,CHR(10),' '),CHR(13),' ') AS SERIAL_NUMBER , 
TYPE_NAME , 
TO_CHAR(A.VENDOR_ID) AS VENDOR_ID , 
R.NAME AS VENDOR_NAME,
TO_CHAR(A.VENDRETURN_VARIANCE_ACCOUNT_ID) AS VENDRETURN_VARIANCE_ACCOUNT_ID,
S.LIST_ITEM_NAME AS PRODUCT_CATEGORY,
T.LIST_ITEM_NAME AS ITEM_TYPE,
U.CODE||' '||U.PRODUCT_CLASSIFICATION_ANZ_NAM AS PRODUCT_CLASSIFICATION,
V.PRODUCT_TYPE_LISTANZ_NAME AS PRODUCT_TYPE,
W.LIST_ITEM_NAME AS PRODUCT_SERIESFAMILY,
REPLACE(REPLACE(A.WANG_ITEM_CODE,CHR(10),' '),CHR(13),' ') AS WANG_ITEM_CODE 
FROM
ITEMS A
LEFT OUTER JOIN ACCOUNTS E ON (A.ASSET_ACCOUNT_ID = E.ACCOUNT_ID)
LEFT OUTER JOIN ACCOUNTS F ON (A.BILL_EXCH_RATE_VAR_ACCOUNT_ID = F.ACCOUNT_ID)
LEFT OUTER JOIN ACCOUNTS G ON (A.BILL_PRICE_VARIANCE_ACCOUNT_ID = G.ACCOUNT_ID)
LEFT OUTER JOIN ACCOUNTS H ON (A.BILL_QTY_VARIANCE_ACCOUNT_ID = H.ACCOUNT_ID)
LEFT OUTER JOIN CLASSES I ON (A.CLASS_ID = I.CLASS_ID)
LEFT OUTER JOIN DEPARTMENTS J ON (A.DEPARTMENT_ID = J.DEPARTMENT_ID)
LEFT OUTER JOIN ACCOUNTS K ON (A.EXPENSE_ACCOUNT_ID = K.ACCOUNT_ID)
LEFT OUTER JOIN ACCOUNTS L ON (A.INCOME_ACCOUNT_ID = L.ACCOUNT_ID)
LEFT OUTER JOIN ISBN M ON (A.ISBN_ID = M.ISBN_ID)
LEFT OUTER JOIN LOCATIONS X ON (A.LOCATION_ID = X.LOCATION_ID)
LEFT OUTER JOIN ITEMS O ON (A.PARENT_ID = O.ITEM_ID)
LEFT OUTER JOIN ACCOUNTS P ON (A.PROD_PRICE_VAR_ACCOUNT_ID = P.ACCOUNT_ID)
LEFT OUTER JOIN ACCOUNTS Q ON (A.PROD_QTY_VAR_ACCOUNT_ID = Q.ACCOUNT_ID)
LEFT OUTER JOIN VENDORS R ON (A.VENDOR_ID = R.VENDOR_ID)
LEFT OUTER JOIN PRODUCT_CATEGORY_LIST S ON (A.PRODUCT_CATEGORY_ID = S.LIST_ID)
LEFT OUTER JOIN ITEM_TYPE_LIST T ON (A.ITEM_TYPE_ID = T.LIST_ID)
LEFT OUTER JOIN PRODUCT_CLASSIFICATION_ANZ U ON (A.PRODUCT_CLASSIFICATION_ID = U.PRODUCT_CLASSIFICATION_ANZ_ID)
LEFT OUTER JOIN PRODUCT_TYPE_LISTANZ V ON (A.PRODUCT_TYPE_ANZ_ID = V.PRODUCT_TYPE_LISTANZ_ID)
LEFT OUTER JOIN PRODUCT_SERIESFAMILY_LIST W ON (A.PRODUCT_SERIESFAMILY_ID = W.LIST_ID)
where not exists ( select 1 from tax_items D
where D.item_id = A.item_id )
AND A.ISINACTIVE = 'No'
ORDER BY A.ITEM_ID;



