SELECT
 TRANID AS DOCUMENT_NUMBER
,TRANSACTION_NUMBER
,TRANSACTION_ID
,BOOK_FAIRS_CONSULTANT_ID AS SALES_REP_ID
,SALES_REP_ID AS TERRITORY_ID
,OPEN_DATE
,SHIP_DATE
,CLOSE_DATE
,RETURN_DATE
,FORECAST_TYPE
,ABCDO_MARKER_ID
,BOOK_FAIRS_STATUS_ID
,BOOK_FAIR_TYPE_ID
,TRUCK_ROUTE_ID
,BOOK_FAIRS_INV__OPTIONS_ID AS INVOICE_OPTION_ID
,c.BILL_ADDRESS_LINE_1
,c.BILL_ADDRESS_LINE_2
,c.BILL_ADDRESS_LINE_3
,c.BILL_CITY
,c.BILL_COUNTRY
,c.BILL_STATE
,c.BILL_ZIP
,c.SHIP_ADDRESS_LINE_1
,c.SHIP_ADDRESS_LINE_2
,c.SHIP_ADDRESS_LINE_3
,c.SHIP_CITY
,c.SHIP_COUNTRY
,c.SHIP_STATE
,c.SHIP_ZIP
,STATUS
,CURRENCY_ID
,TRANDATE
,EXCHANGE_RATE
,ROLL_SIZE
,PROJECTED_TOTAL
,WEIGHTED_TOTAL
,LOCATION_ID
,B.SUBSIDIARY_ID AS SUBSIDIARY_ID
,ACCOUNTING_PERIOD_ID
,ENTITY_ID AS CUSTOMER_ID
,CUSTOM_FORM_ID
,CREATED_BY_ID
,CREATE_DATE
,DATE_LAST_MODIFIED
FROM
 TRANSACTIONS A
 INNER JOIN transaction_lines b ON (TRANSACTIONS.transaction_id = b.transaction_id)
 LEFT OUTER JOIN transaction_address c ON (TRANSACTIONS.transaction_id = transaction_address.transaction_id)
 INNER JOIN accounts d ON (b.account_id = d.account_id)
WHERE A.TRANSACTION_TYPE = 'Opportunity'
AND B.SUBSIDIARY_ID = '%s'
AND d.name = 'Opportunities'
AND A.DATE_LAST_MODIFIED >= to_timestamp('%s','YYYY-MM-DD HH24:MI:SS')
ORDER BY TRANDATE, OPEN_DATE ,SUBSIDIARY_ID, DOCUMENT_NUMBER,TRANSACTION_ID;
