SELECT
 TRANID AS DOCUMENT_NUMBER
,TRANSACTION_NUMBER
,TO_CHAR(TRANSACTION_ID) AS TRANSACTION_ID
,TO_CHAR(BOOK_FAIRS_CONSULTANT_ID) AS SALES_REP_ID
,TO_CHAR(e.SALES_TERRITORY_ID) AS TERRITORY_ID 
,OPEN_DATE
,SHIP_DATE
,CLOSE_DATE
,RETURN_DATE
,FORECAST_TYPE
,TO_CHAR(ABCDO_MARKER_ID) ABCDO_MARKER_ID
,TO_CHAR(BOOK_FAIRS_STATUS_ID) BOOK_FAIRS_STATUS_ID
,TO_CHAR(BOOK_FAIR_TYPE_ID) BOOK_FAIR_TYPE_ID
,TO_CHAR(TRUCK_ROUTE_ID) TRUCK_ROUTE_ID
,TO_CHAR(BOOK_FAIRS_INV__OPTIONS_ID)  AS INVOICE_OPTION_ID
,c.BILL_ADDRESS_LINE_1
,c.BILL_ADDRESS_LINE_2
,c.BILL_ADDRESS_LINE_3
,c.BILL_CITY
,c.BILL_COUNTRY
,c.BILL_STATE
,c.BILL_ZIP
,c.SHIP_ADDRESS_LINE_1
,c.SHIP_ADDRESS_LINE_2
,c.SHIP_ADDRESS_LINE_3
,c.SHIP_CITY
,c.SHIP_COUNTRY
,c.SHIP_STATE
,c.SHIP_ZIP
,STATUS
,TO_CHAR(CURRENCY_ID) AS CURRENCY_ID
,TRANDATE
,EXCHANGE_RATE
,ROLL_SIZE
,PROJECTED_TOTAL
,WEIGHTED_TOTAL
,TO_CHAR(LOCATION_ID) AS LOCATION_ID
,TO_CHAR(B.SUBSIDIARY_ID) AS SUBSIDIARY_ID
,TO_CHAR(ACCOUNTING_PERIOD_ID) AS ACCOUNTING_PERIOD_ID
,TO_CHAR(ENTITY_ID) AS CUSTOMER_ID
,TO_CHAR(CUSTOM_FORM_ID) AS CUSTOM_FORM_ID
,TO_CHAR(CREATED_BY_ID) AS CREATED_BY_ID
,CREATE_DATE
,DATE_LAST_MODIFIED
FROM
 TRANSACTIONS A
 INNER JOIN transaction_lines b ON (TRANSACTIONS.transaction_id = b.transaction_id)
 LEFT OUTER JOIN transaction_address c ON (TRANSACTIONS.transaction_id = transaction_address.transaction_id)
 LEFT OUTER JOIN employees e ON (TRANSACTIONS.sales_rep_id = employees.employee_id) 
 INNER JOIN accounts d ON (b.account_id = d.account_id)
WHERE A.TRANSACTION_TYPE = 'Opportunity'
AND B.SUBSIDIARY_ID = '%s'
AND d.name = 'Opportunities'
AND A.DATE_LAST_MODIFIED >= to_timestamp('%s','YYYY-MM-DD HH24:MI:SS')
ORDER BY TRANDATE, OPEN_DATE ,SUBSIDIARY_ID, DOCUMENT_NUMBER , TRANSACTION_ID ;
