CREATE SCHEMA if not exists dw;

DROP TABLE if exists dw.freight_estimate;

CREATE TABLE dw.freight_estimate 
(
  FREIGHT_KEY                     BIGINT IDENTITY(0,1),
  LANDED_COST_RULE_MATRIX_NZ_ID   INTEGER,
  SHIP_METHOD_NAME                VARCHAR(1000),
  SHIP_METHOD_DESCRIPTION         VARCHAR(4000),
  IS_INACTIVE                     VARCHAR(10),
  PERCENT_OF_COST                 INTEGER,
  ADDITIONAL_AMOUNT               INTEGER,
  SUBSIDIARY                      VARCHAR(100),
  SUBSIDIARY_ID                   INTEGER,
  DATE_ACTIVE_FROM                TIMESTAMP,
  DATE_ACTIVE_TO                  TIMESTAMP,
  DW_ACTIVE                       VARCHAR(1),
  PRIMARY KEY (FREIGHT_KEY,LANDED_COST_RULE_MATRIX_NZ_ID,DW_ACTIVE)
)
DISTSTYLE ALL INTERLEAVED SORTKEY (FREIGHT_KEY,LANDED_COST_RULE_MATRIX_NZ_ID,DW_ACTIVE);

INSERT INTO dw.freight_estimate
(
  LANDED_COST_RULE_MATRIX_NZ_ID,
  SHIP_METHOD_NAME,
  SHIP_METHOD_DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  ADDITIONAL_AMOUNT,
  SUBSIDIARY,
  SUBSIDIARY_ID,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE
)
SELECT -99 AS LANDED_COST_RULE_MATRIX_NZ_ID,
       'NA_GDW' AS SHIP_METHOD_NAME,
       'NA_GDW' AS SHIP_METHOD_DESCRIPTION,
       'NA_GDW' AS IS_INACTIVE,
       -99 AS PERCENT_OF_COST,
       -99 AS ADDITIONAL_AMOUNT,
       'NA_GDW' AS SUBSIDIARY,
       -99 AS SUBSIDIARY_ID,
       SYSDATE AS DATE_ACTIVE_FROM,
       '9999-12-31 12:59:59' AS DATE_ACTIVE_TO,
       'A' AS DW_ACTIVE;

INSERT INTO dw.freight_estimate
(
  LANDED_COST_RULE_MATRIX_NZ_ID,
  SHIP_METHOD_NAME,
  SHIP_METHOD_DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  ADDITIONAL_AMOUNT,
  SUBSIDIARY,
  SUBSIDIARY_ID,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE
)
SELECT 0 AS LANDED_COST_RULE_MATRIX_NZ_ID,
       'NA_ERR' AS SHIP_METHOD_NAME,
       'NA_ERR' AS SHIP_METHOD_DESCRIPTION,
       'NA_ERR' AS IS_INACTIVE,
       0 AS PERCENT_OF_COST,
       0 AS ADDITIONAL_AMOUNT,
       'NA_ERR' AS SUBSIDIARY,
       0 AS SUBSIDIARY_ID,
       SYSDATE AS DATE_ACTIVE_FROM,
       '9999-12-31 12:59:59' AS DATE_ACTIVE_TO,
       'A' AS DW_ACTIVE;

COMMIT;

