INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '1',
  'USA AIR',
  'AA',
  'F',
  50.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-07-20 18:22:45'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '2',
  'USA SEA',
  'AS',
  'F',
  28.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-07-20 18:23:02'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '3',
  'CANADA AIR',
  'BA',
  'F',
  50.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:55:43'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '4',
  'CANADA SEA',
  'BS',
  'F',
  30.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:55:50'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '5',
  'UNITED KINGDOM AIR',
  'CA',
  'F',
  30.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:57:07'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '6',
  'UNITED KINGDOM SEA',
  'CS',
  'F',
  15.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:57:14'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '7',
  'AS2',
  'EA',
  'F',
  16.0,
  6.0,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-08-19 10:09:50'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '8',
  'AUSTRALIA SEA',
  'ES',
  'F',
  15.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:55:36'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '9',
  'CHINA / HONG KONG AIR',
  'FA',
  'F',
  40.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:55:56'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '10',
  'CHINA / HONG KONG SEA',
  'FS',
  'F',
  10.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:56:02'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '11',
  'SINGAPORE AIR',
  'GA',
  'F',
  45.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:56:43'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '12',
  'SINGAPORE SEA',
  'GS',
  'F',
  10.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:56:48'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '13',
  'MALAYSIA AIR',
  'MA',
  'F',
  40.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:56:13'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '14',
  'MALAYSIA SEA',
  'MS',
  'F',
  10.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:56:28'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '15',
  'IRE/UK/CAN',
  'EUC',
  'F',
  12.0,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:56:07'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '16',
  'NM EX ASIA',
  'NMA',
  'F',
  2.5,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:56:33'
);

INSERT INTO dw_prestage.freight_estimate
(
  runid,
  LANDED_COST_RULE_MATRIX_NZ_ID,
  LANDED_COST_RULE_MATRIX_NZ_NAM,
  DESCRIPTION,
  IS_INACTIVE,
  PERCENT_OF_COST,
  PLUS_AMOUNT,
  SUBSIDIARY_ID,
  SUBSIDIARY,
  DATE_CREATED,
  LAST_MODIFIED_DATE
)
VALUES
(
  1,
  '17',
  'NZ/ASIA',
  'NZA',
  'F',
  6.5,
  NULL,
  '27',
  'Scholastic New Zealand Limited',
  '2015-06-29 10:34:43',
  '2015-06-29 13:56:38'
);


COMMIT;
