CREATE SCHEMA if not exists dw;

DROP TABLE if exists dw.classes;

CREATE TABLE dw.classes 
(
  CLASS_KEY               BIGINT IDENTITY(0,1),
  CLASS_ID                INTEGER,
  ISINACTIVE              VARCHAR(10),
  ACCPAC_LOB_CODES        VARCHAR(4000),
  HYPERION_LOB_CODES      VARCHAR(4000),
  LINE_OF_BUSINESS_CODE   VARCHAR(4000),
  NAME                    VARCHAR(31),
  PARENT_ID               INTEGER,
  DATE_ACTIVE_FROM        TIMESTAMP,
  DATE_ACTIVE_TO          TIMESTAMP,
  DW_ACTIVE               VARCHAR(1),
  PARENT_NAME             VARCHAR(83),
  PRIMARY KEY (CLASS_KEY)
)
DISTSTYLE ALL INTERLEAVED SORTKEY (CLASS_KEY,CLASS_ID,LINE_OF_BUSINESS_CODE,NAME,DW_ACTIVE);

INSERT INTO dw.classes
(
  CLASS_ID,
  ISINACTIVE,
  ACCPAC_LOB_CODES,
  HYPERION_LOB_CODES,
  LINE_OF_BUSINESS_CODE,
  NAME,
  PARENT_ID,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE,
  PARENT_NAME
)
SELECT -99 AS CLASS_ID,
       'No' AS ISINACTIVE,
       'NA_GDW' AS ACCPAC_LOB_CODES,
       'NA_GDW' AS HYPERION_LOB_CODES,
       'NA_GDW' AS LINE_OF_BUSINESS_CODE,
       'NA_GDW' AS NAME,
       -99 AS PARENT_ID,
       SYSDATE AS DATE_ACTIVE_FROM,
       '9999-12-31 23:59:59' AS DATE_ACTIVE_TO,
       'A' AS dw_active,
       'NA_GDW' AS PARENT_NAME;

INSERT INTO dw.classes
(
  CLASS_ID,
  ISINACTIVE,
  ACCPAC_LOB_CODES,
  HYPERION_LOB_CODES,
  LINE_OF_BUSINESS_CODE,
  NAME,
  PARENT_ID,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE,
  PARENT_NAME
)
SELECT 0 AS CLASS_ID,
       'No' AS ISINACTIVE,
       'NA_ERR' AS ACCPAC_LOB_CODES,
       'NA_ERR' AS HYPERION_LOB_CODES,
       'NA_ERR' AS LINE_OF_BUSINESS_CODE,
       'NA_ERR' AS NAME,
       0 AS PARENT_ID,
       SYSDATE AS DATE_ACTIVE_FROM,
       '9999-12-31 23:59:59' AS DATE_ACTIVE_TO,
       'A' AS dw_active,
       'NA_ERR' AS PARENT_NAME;

