SELECT
REPLACE(REPLACE(CLASSES.ACCPAC_LOB_CODES,CHR(10),' '),CHR(13),' ') AS ACCPAC_LOB_CODES , 
REPLACE(REPLACE(CLASSES.CLASS_EXTID,CHR(10),' '),CHR(13),' ') AS CLASS_EXTID , 
TO_CHAR(CLASSES.CLASS_ID) AS CLASS_ID , 
TO_CHAR(CLASSES.DATE_LAST_MODIFIED,'YYYY-MM-DD HH24:MI:SS') AS DATE_LAST_MODIFIED , 
REPLACE(REPLACE(CLASSES.FULL_NAME,CHR(10),' '),CHR(13),' ') AS FULL_NAME , 
REPLACE(REPLACE(CLASSES.HYPERION_LOB_CODES,CHR(10),' '),CHR(13),' ') AS HYPERION_LOB_CODES , 
ISINACTIVE , 
REPLACE(REPLACE(CLASSES.LINE_OF_BUSINESS_CODE,CHR(10),' '),CHR(13),' ') AS LINE_OF_BUSINESS_CODE , 
NAME , 
TO_CHAR(CLASSES.PARENT_ID) AS PARENT_ID 
FROM
CLASSES;


