CREATE SCHEMA if not exists dw;

DROP TABLE if exists dw.po_fact;

CREATE TABLE dw.po_fact 
(
  PO_KEY                        BIGINT IDENTITY(0,1),
  PO_NUMBER                     VARCHAR(150),
  VENDOR_KEY                    INTEGER,
  REQUESTER_KEY                 INTEGER,
  APPROVER_LEVEL1_KEY           INTEGER,
  APPROVER_LEVEL2_KEY           INTEGER,
  RECEIVE_DATE_KEY              INTEGER,
  CREATE_DATE_KEY               INTEGER,
  SUBSIDIARY_KEY                INTEGER,
  LOCATION_KEY                  INTEGER,
  COST_CENTER_KEY               INTEGER,
  EXCHANGE_RATE                 NUMBER(30,15),
  ITEM_KEY                      INTEGER,
  VENDOR_ITEM_KEY               INTEGER,
  BILLADDRESS                   VARCHAR(1000),
  SHIPADDRESS                   VARCHAR(1000),
  QUANTITY                      NUMBER(18,8),
  BIH_QUANTITY                  NUMBER(22),
  BC_QUANTITY                   NUMBER(22),
  TRADE_QUANTITY                NUMBER(22),
  NZSO_QUANTITY                 NUMBER(22),
  EDUCATION_QUANTITY            NUMBER(22),
  SCHOOL_ESSENTIALS_QUANTITY    NUMBER(22),
  BOOK_FAIR_QUANTITY            NUMBER(22),
  RATE                          VARCHAR(50),
  AMOUNT                        NUMBER(20,2),
  ITEM_GROSS_AMOUNT             NUMBER(20,2),
  AMOUNT_FOREIGN                DECIMAL(22,2),
  NET_AMOUNT                    DECIMAL(22,2),
  NET_AMOUNT_FOREIGN            DECIMAL(22,2),
  GROSS_AMOUNT                  DECIMAL(22,2),
  MATCH_BILL_TO_RECEIPT         VARCHAR(10),
  TRACK_LANDED_COST             VARCHAR(10),
  TAX_ITEM_KEY                  INTEGER,
  TAX_AMOUNT                    NUMBER(20,2),
  REQUESTED_RECEIPT_DATE_KEY    INTEGER,
  ACTUAL_DELIVERY_DATE_KEY      INTEGER,
  FREIGHT_ESTIMATE_METHOD_KEY   INTEGER,
  FREIGHT_RATE                  NUMBER(22),
  CARRIER_KEY                   INTEGER,
  TERMS_KEY                     INTEGER,
  PO_TYPE                       VARCHAR(50),
  STATUS                        VARCHAR(100),
  APPROVAL_STATUS               VARCHAR(4000),
  CREATION_DATE                 TIMESTAMP,
  LAST_MODIFIED_DATE            TIMESTAMP,
  VALID_TILL_DATE               DATE,
  ACTIVE                        VARCHAR(10),
  CURRENCY_KEY                  INTEGER,
  PRIMARY KEY (PO_KEY,PO_NUMBER))
DISTSTYLE ALL INTERLEAVED SORTKEY (PO_KEY,PO_NUMBER);

