SELECT
       TO_CHAR(D.TRANSACTION_ID) AS TRANSACTION_ID,
	   REPLACE(REPLACE(D.TRANID,CHR (10),' '),CHR (13),' ') AS DOCUMENT_NUMBER,
       REPLACE(REPLACE(D.TRANSACTION_NUMBER,CHR (10),' '),CHR (13),' ') AS PO_NUMBER,
       TO_CHAR(TRANSACTION_LINES.TRANSACTION_LINE_ID) AS TRANSACTION_LINE_ID,
       F.TRANSACTION_NUMBER AS REF_TRX_NUMBER,  
       TO_CHAR(F.CUSTOM_FORM_ID) AS REF_CUSTOM_FORM_ID,      
       TO_CHAR(D.ENTITY_ID) AS VENDOR_ID,
       TO_CHAR(D.APPROVER_LEVEL_ONE_ID) AS APPROVER_LEVEL_ONE_ID,
       TO_CHAR(D.APPROVER_LEVEL_TWO_ID) AS APPROVER_LEVEL_TWO_ID,
       D.AMOUNT_UNBILLED,
       REPLACE(REPLACE(D.APPROVAL_STATUS,CHR (10),' '),CHR (13),' ') AS APPROVAL_STATUS,
       e.bill_address_line_1,
       e.bill_address_line_2,
       e.bill_address_line_3,
       e.bill_city,
       e.bill_country,
       e.bill_state,
       e.bill_zip,
       TO_CHAR(D.CARRIER_LEBEL_ID) AS CARRIER_ID,  
       TO_CHAR(D.CLOSED,'YYYY-MM-DD HH24:MI:SS') AS CLOSED,
       TO_CHAR(D.CREATED_BY_ID) AS CREATED_BY_ID,
       TO_CHAR(D.SALES_REP_ID) AS REQUESTOR_ID,
       TO_CHAR(D.CREATED_FROM_ID) AS CREATED_FROM_ID,
       TO_CHAR(D.CREATE_DATE,'YYYY-MM-DD HH24:MI:SS') AS CREATE_DATE,
	   TO_CHAR(D.TRANDATE,'YYYY-MM-DD HH24:MI:SS') AS TRANDATE,
       TO_CHAR(D.CURRENCY_ID) AS CURRENCY_ID,
       TO_CHAR(D.CUSTOM_FORM_ID) AS CUSTOM_FORM_ID,
       TO_CHAR(D.DATE_LAST_MODIFIED,'YYYY-MM-DD HH24:MI:SS') AS DATE_LAST_MODIFIED,
       TO_CHAR(D.EMPLOYEE_CUSTOM_ID) AS EMPLOYEE_CUSTOM_ID,
       D.EXCHANGE_RATE,
       TO_CHAR(D.LOCATION_ID) AS LOCATION_ID,
       TO_CHAR(D.PO_APPROVER_ID) AS PO_APPROVER_ID,
       e.ship_address_line_1,
       e.ship_address_line_2,
       e.ship_address_line_3,
       e.ship_city,
       e.ship_country,
       e.ship_state,
       e.ship_zip,
       TO_CHAR(TRANSACTION_LINES.SHIPMENT_RECEIVED,'YYYY-MM-DD HH24:MI:SS') AS SHIPMENT_RECEIVED,
       REPLACE(REPLACE(D.STATUS,CHR (10),' '),CHR (13),' ') AS PO_STATUS,
       TO_CHAR(D.PAYMENT_TERMS_ID) AS PAYMENT_TERMS_ID,
       TRANSACTION_LINES.FRIGHT_RATE,
       TO_CHAR(TRANSACTION_LINES.SUBSIDIARY_ID) AS SUBSIDIARY_ID,
       TO_CHAR(TRANSACTION_LINES.DEPARTMENT_ID) AS DEPARTMENT_ID,
       TO_CHAR(TRANSACTION_LINES.ITEM_ID) AS ITEM_ID,
       TO_CHAR(TRANSACTION_LINES.BC_QUANTITY) AS BC_QUANTITY,
       TO_CHAR(TRANSACTION_LINES.BIH_QUANTITY) AS BIH_QUANTITY,
       TO_CHAR(TRANSACTION_LINES.BOOK_FAIR_QUANTITY) AS BOOK_FAIR_QUANTITY,
       TO_CHAR(TRANSACTION_LINES.EDUCATION_QUANTITY) AS EDUCATION_QUANTITY,
       TO_CHAR(TRANSACTION_LINES.NZSO_QUANTITY) AS NZSO_QUANTITY,
       TO_CHAR(TRANSACTION_LINES.TRADE_QUANTITY) AS TRADE_QUANTITY,
       TO_CHAR(TRANSACTION_LINES.SCHOOL_ESSENTIALS_QUANTITY) AS SCHOOL_ESSENTIALS_QUANTITY,
       TO_CHAR(TRANSACTION_LINES.ITEM_COUNT) AS ITEM_COUNT,
       TO_CHAR(TRANSACTION_LINES.ITEM_GROSS_AMOUNT) AS ITEM_GROSS_AMOUNT,
       TO_CHAR(TRANSACTION_LINES.AMOUNT) AS AMOUNT,
       TO_CHAR(TRANSACTION_LINES.AMOUNT_FOREIGN) AS AMOUNT_FOREIGN,
       TO_CHAR(TRANSACTION_LINES.NET_AMOUNT) AS NET_AMOUNT,
       TO_CHAR(TRANSACTION_LINES.NET_AMOUNT_FOREIGN) AS NET_AMOUNT_FOREIGN,
       TO_CHAR(TRANSACTION_LINES.GROSS_AMOUNT) AS GROSS_AMOUNT,
       TO_CHAR(TRANSACTION_LINES.MATCH_BILL_TO_RECEIPT) AS MATCH_BILL_TO_RECEIPT,
       TO_CHAR(TRANSACTION_LINES.TRACK_LANDED_COST) AS TRACK_LANDED_COST,
       TO_CHAR(TRANSACTION_LINES.ITEM_UNIT_PRICE) AS ITEM_UNIT_PRICE,
       TO_CHAR(TRANSACTION_LINES.NUMBER_BILLED) AS NUMBER_BILLED,
       TO_CHAR(TRANSACTION_LINES.QUANTITY_RECEIVED_IN_SHIPMENT ) AS QUANTITY_RECEIVED_IN_SHIPMENT ,
       TO_CHAR(TRANSACTION_LINES.QUANTITY_RETURNED ) AS QUANTITY_RETURNED ,
       TO_CHAR(TRANSACTION_LINES.EXPECTED_RECEIPT_DATE,'YYYY-MM-DD HH24:MI:SS') AS EXPECTED_RECEIPT_DATE,
       TO_CHAR(TRANSACTION_LINES.ACTUAL_DELIVERY_DATE,'YYYY-MM-DD HH24:MI:SS') AS ACTUAL_DELIVERY_DATE,
       TO_CHAR(TRANSACTION_LINES.TAX_ITEM_ID) AS TAX_ITEM_ID,
       TRANSACTION_LINES.TAX_TYPE,
       C.AMOUNT AS TAX_AMOUNT,
       TO_CHAR(TRANSACTION_LINES.FREIGHT_ESTIMATE_METHOD_ID) AS FREIGHT_ESTIMATE_METHOD_ID,
       Decode(b.name,
             'Purchase Orders','PO_HDR',
             decode(a.transaction_line_id,0,'PO_HDR',decode(c.transaction_line_id,NULL,decode(i.item_id,NULL,'PO_LINE','PO_TAX'),'PO_LINE'))
       )  AS line_type,
       TO_CHAR(TRANSACTION_LINES.CLASS_ID) as CLASS_ID
FROM TRANSACTION_LINES a
  LEFT OUTER JOIN accounts b ON (TRANSACTION_LINES.account_id = accounts.account_id)
  LEFT OUTER JOIN transaction_tax_detail c
               ON (TRANSACTION_LINES.transaction_id = transaction_tax_detail.transaction_id
              AND TRANSACTION_LINES.transaction_line_id = transaction_tax_detail.transaction_line_id)
  LEFT OUTER JOIN transaction_address e ON (TRANSACTION_LINES.transaction_id = transaction_address.transaction_id)
  INNER JOIN transactions d ON (TRANSACTION_LINES.transaction_id = transactions.transaction_id)
  LEFT OUTER JOIN transactions f ON (d.created_from_id = f.transaction_id)
  LEFT OUTER JOIN tax_items i ON (a.item_id = i.item_id)
WHERE transactions.transaction_type = 'Purchase Order'
AND   transaction_lines.subsidiary_id = '%s'
AND EXISTS (SELECT 1
              FROM transactions i
              WHERE i.transaction_id = TRANSACTION_LINES.transaction_id
              AND   i.transaction_type = 'Purchase Order'
	      AND i.date_last_modified >= to_timestamp('%s','YYYY-MM-DD HH24:MI:SS'))
ORDER BY TRANSACTION_LINES.transaction_id,
         TRANSACTION_LINES.transaction_line_id;
