/* error prestage - drop intermediate error prestage table */
DROP TABLE IF EXISTS DW_PRESTAGE.PO_FACT_ERROR;

/* prestage - create intermediate insert table*/
CREATE TABLE DW_PRESTAGE.PO_FACT_ERROR
AS
SELECT
A.runid
,A.PO_NUMBER
,A.PO_ID
,A.PO_LINE_ID
,A.ref_trx_number
,NVL(A.REF_TRX_TYPE_KEY,U.TRANSACTION_TYPE_KEY)  REF_TRX_TYPE_KEY
,NVL(A.VENDOR_KEY, B.VENDOR_KEY ) AS   VENDOR_KEY
,NVL( A.REQUESTER_KEY, C.EMPLOYEE_KEY)  AS REQUESTER_KEY
,NVL( A.APPROVER_LEVEL1_KEY, D.EMPLOYEE_KEY)  AS  APPROVER_LEVEL1_KEY
,NVL( A.  APPROVER_LEVEL2_KEY, D1.EMPLOYEE_KEY)  AS  APPROVER_LEVEL2_KEY
,NVL(F.DATE_KEY , A.CREATE_DATE_KEY) AS   CREATE_DATE_KEY
,NVL( A.SUBSIDIARY_KEY , G.SUBSIDIARY_KEY ) AS SUBSIDIARY_KEY
,NVL( A.LOCATION_KEY, L.LOCATION_KEY ) AS LOCATION_KEY
,NVL( A. COST_CENTER_KEY, R.DEPARTMENT_KEY ) AS COST_CENTER_KEY
,NVL( A.ITEM_KEY , M.ITEM_KEY ) AS ITEM_KEY
,NVL( A.REQUESTED_RECEIPT_DATE_KEY  , H.DATE_KEY ) AS REQUESTED_RECEIPT_DATE_KEY
,NVL(A.ACTUAL_DELIVERY_DATE_KEY , I.DATE_KEY ) AS ACTUAL_DELIVERY_DATE_KEY
,NVL( A.FREIGHT_ESTIMATE_METHOD_KEY , J.FREIGHT_KEY ) AS FREIGHT_ESTIMATE_METHOD_KEY
,NVL( A.TERMS_KEY , P.PAYMENT_TERM_KEY ) AS TERMS_KEY
,NVL( A.TAX_ITEM_KEY , Q.TAX_ITEM_KEY ) AS TAX_ITEM_KEY
,NVL( A.CURRENCY_KEY , K.CURRENCY_KEY ) AS CURRENCY_KEY
,NVL( A.CLASS_KEY , S.CLASS_KEY ) AS CLASS_KEY
,NVL( A.CARRIER_KEY , T.CARRIER_KEY ) AS CARRIER_KEY
,A.EXCHANGE_RATE
,A.BILL_ADDRESS_LINE_1
,A.BILL_ADDRESS_LINE_2
,A.BILL_ADDRESS_LINE_3
,A.BILL_CITY
,A.BILL_COUNTRY
,A.BILL_STATE
,A.BILL_ZIP
,A.SHIP_ADDRESS_LINE_1
,A.SHIP_ADDRESS_LINE_2
,A.SHIP_ADDRESS_LINE_3
,A.SHIP_CITY
,A.SHIP_COUNTRY
,A.SHIP_STATE
,A.SHIP_ZIP
,A.QUANTITY
,A.BIH_QUANTITY
,A.BC_QUANTITY
,A.TRADE_QUANTITY
,A.NZSO_QUANTITY
,A.EDUCATION_QUANTITY
,A.SCHOOL_ESSENTIALS_QUANTITY
,A.BOOK_FAIR_QUANTITY
,A.NUMBER_BILLED
,A.QUANTITY_RECEIVED_IN_SHIPMENT
,A.QUANTITY_RETURNED
,A.RATE
,A.AMOUNT
,A.ITEM_GROSS_AMOUNT
,A.AMOUNT_FOREIGN
,A.NET_AMOUNT
,A.NET_AMOUNT_FOREIGN
,A.GROSS_AMOUNT
,A.MATCH_BILL_TO_RECEIPT
,A.TRACK_LANDED_COST
,A.TAX_AMOUNT
,A.FREIGHT_RATE
,NVL(A.PO_TYPE_KEY , W.transaction_type_key ) AS PO_TYPE_KEY  
,NVL(A.  PO_STATUS_KEY, V.transaction_status_key ) AS  PO_STATUS_KEY
,A.APPROVAL_STATUS
,A.CREATION_DATE
,A.LAST_MODIFIED_DATE
,'PROCESSED'  RECORD_STATUS
,SYSDATE  DW_CREATION_DATE 
FROM dw.po_fact_error A
  INNER JOIN DW_REPORT.VENDORS B ON (A.VENDOR_ID = B.VENDOR_ID)                                                             
  INNER JOIN DW_REPORT.EMPLOYEES C ON (NVL (A.REQUESTER_ID,-99) = C.EMPLOYEE_ID)                                            
  INNER JOIN DW_REPORT.EMPLOYEES D ON (NVL (A.APPROVER_LEVEL1_ID,-99) = D.EMPLOYEE_ID)                                   
  INNER JOIN DW_REPORT.EMPLOYEES D1 ON (NVL (A.APPROVER_LEVEL2_ID,-99) = D1.EMPLOYEE_ID)                                 
  INNER JOIN DW_REPORT.DWDATE F ON (TO_CHAR (A.CREATION_DATE,'YYYYMMDD') = F.DATE_ID)                                         
  INNER JOIN DW_REPORT.SUBSIDIARIES G ON (NVL (A.SUBSIDIARY_ID,-99) = G.SUBSIDIARY_ID)                                      
  INNER JOIN DW_REPORT.DWDATE H ON (NVL (TO_CHAR (A.REQUESTED_RECEIPT_DATE,'YYYYMMDD'),'19000101') = H.DATE_ID)              
  INNER JOIN DW_REPORT.DWDATE I ON (NVL (TO_CHAR (A.ACTUAL_DELIVERY_DATE,'YYYYMMDD'),'19000101') = I.DATE_ID)               
  INNER JOIN DW_REPORT.FREIGHT_ESTIMATE J ON (NVL (A.FREIGHT_ESTIMATE_METHOD_ID,-99) = J.LANDED_COST_RULE_MATRIX_NZ_ID)     
  INNER JOIN DW_REPORT.CURRENCIES K ON (A.CURRENCY_ID = K.CURRENCY_ID)                                                      
  INNER JOIN DW_REPORT.LOCATIONS L ON (NVL(A.LOCATION_ID,-99) = L.LOCATION_ID)                                              
  INNER JOIN DW_REPORT.ITEMS M ON (A.ITEM_ID = M.ITEM_ID)                                                                   
  INNER JOIN DW_REPORT.PAYMENT_TERMS P ON (NVL (A.TERMS_ID,-99) = P.PAYMENT_TERMS_ID)                               
  INNER JOIN DW_REPORT.TAX_ITEMS Q ON (A.TAX_ITEM_ID = Q.ITEM_ID)                                                           
  INNER JOIN DW_REPORT.COST_CENTER R ON (NVL (A.COST_CENTER_ID,-99) = R.DEPARTMENT_ID)                                       
  INNER JOIN DW_REPORT.CLASSES S ON (NVL (A.CLASS_ID,-99) = S.CLASS_ID)                                                     
  INNER JOIN DW_REPORT.CARRIER T ON (NVL (A.CARRIER_ID,-99) = T.CARRIER_ID)                                                 
  INNER JOIN DW_REPORT.transaction_type U ON (NVL(A.ref_custom_form_id,-99) = U.transaction_type_id)                        
  INNER JOIN DW_REPORT.transaction_status V ON (NVL(A.PO_STATUS,'NA_GDW') = V.status AND V.DOCUMENT_TYPE = 'Purchase Order')
  INNER JOIN DW_REPORT.transaction_type W ON (A.custom_form_id = W.transaction_type_id) 
  WHERE A.RUNID = NVL('%s',A.RUNID)
  AND A.RECORD_STATUS  = 'ERROR';

/* prestage-> identify new po fact records */
UPDATE DW_PRESTAGE.PO_FACT_ERROR
 SET RECORD_STATUS = 'INSERT'
 WHERE NOT EXISTS
 (SELECT 1 FROM DW_REPORT.PO_FACT B
 WHERE DW_PRESTAGE.PO_FACT_ERROR.TRANSACTION_ID = B.TRANSACTION_ID
 AND DW_PRESTAGE.PO_FACT_ERROR.TRANSACTION_LINE_ID = B.TRANSACTION_LINE_ID
 AND DW_PRESTAGE.PO_FACT_ERROR.SUBSIDIARY_KEY = B.SUBSIDIARY_KEY );

/* prestage-> no of po fact records reprocessed in staging*/
SELECT count(1) FROM dw_prestage.po_fact_error;

/* prestage-> no of po fact records identified as new*/
SELECT count(1) FROM dw_prestage.po_fact_error where RECORD_STATUS = 'INSERT';

/* prestage-> no of po fact records identified to be updated*/
SELECT count(1) FROM dw_prestage.po_fact_error where RECORD_STATUS = 'PROCESSED';

/* fact -> INSERT REPROCESSED RECORDS WHICH HAS ALL VALID DIMENSIONS */
INSERT INTO dw.po_fact
(
PO_NUMBER,
  PO_ID,
  PO_LINE_ID,
  REF_TRX_NUMBER,
  REF_TRX_TYPE_KEY, 
  VENDOR_KEY,
  REQUESTER_KEY,
  APPROVER_LEVEL1_KEY,
  APPROVER_LEVEL2_KEY,
  CREATE_DATE_KEY,
  SUBSIDIARY_KEY,
  LOCATION_KEY,
  COST_CENTER_KEY,
  ITEM_KEY,
  REQUESTED_RECEIPT_DATE_KEY,
  ACTUAL_DELIVERY_DATE_KEY,
  FREIGHT_ESTIMATE_METHOD_KEY,
  TERMS_KEY,
  TAX_ITEM_KEY,
  CURRENCY_KEY,
  CLASS_KEY,
  CARRIER_KEY,
  EXCHANGE_RATE,
  BILL_ADDRESS_LINE_1,
  BILL_ADDRESS_LINE_2,
  BILL_ADDRESS_LINE_3,
  BILL_CITY,
  BILL_COUNTRY,
  BILL_STATE,
  BILL_ZIP,
  SHIP_ADDRESS_LINE_1,
  SHIP_ADDRESS_LINE_2,
  SHIP_ADDRESS_LINE_3,
  SHIP_CITY,
  SHIP_COUNTRY,
  SHIP_STATE,
  SHIP_ZIP,
  QUANTITY,
  BIH_QUANTITY,
  BC_QUANTITY,
  TRADE_QUANTITY,
  NZSO_QUANTITY,
  EDUCATION_QUANTITY,
  SCHOOL_ESSENTIALS_QUANTITY,
  BOOK_FAIR_QUANTITY,
  NUMBER_BILLED,
  QUANTITY_RECEIVED_IN_SHIPMENT,
  QUANTITY_RETURNED,
  RATE,
  AMOUNT,
  ITEM_GROSS_AMOUNT,
  AMOUNT_FOREIGN,
  NET_AMOUNT,
  NET_AMOUNT_FOREIGN,
  GROSS_AMOUNT,
  MATCH_BILL_TO_RECEIPT,
  TRACK_LANDED_COST,
  TAX_AMOUNT,
  FREIGHT_RATE,
  PO_TYPE_KEY,   
  PO_STATUS_KEY,    
  APPROVAL_STATUS,
  CREATION_DATE,
  LAST_MODIFIED_DATE,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_CURRENT
)
SELECT
 A.PO_NUMBER,
A.PO_ID,
A.PO_LINE_ID,
A.REF_TRX_NUMBER,
A.REF_TRX_TYPE_KEY, 
A.VENDOR_KEY,
A.REQUESTER_KEY,
A.APPROVER_LEVEL1_KEY,
A.APPROVER_LEVEL2_KEY,
A.CREATE_DATE_KEY,
A.SUBSIDIARY_KEY,
A.LOCATION_KEY,
A.COST_CENTER_KEY,
A.ITEM_KEY,
A.REQUESTED_RECEIPT_DATE_KEY,
A.ACTUAL_DELIVERY_DATE_KEY,
A.FREIGHT_ESTIMATE_METHOD_KEY,
A.TERMS_KEY,
A.TAX_ITEM_KEY,
A.CURRENCY_KEY,
A.CLASS_KEY,
A.CARRIER_KEY,
A.EXCHANGE_RATE,
A.BILL_ADDRESS_LINE_1,
A.BILL_ADDRESS_LINE_2,
A.BILL_ADDRESS_LINE_3,
A.BILL_CITY,
A.BILL_COUNTRY,
A.BILL_STATE,
A.BILL_ZIP,
A.SHIP_ADDRESS_LINE_1,
A.SHIP_ADDRESS_LINE_2,
A.SHIP_ADDRESS_LINE_3,
A.SHIP_CITY,
A.SHIP_COUNTRY,
A.SHIP_STATE,
A.SHIP_ZIP,
A.QUANTITY,
A.BIH_QUANTITY,
A.BC_QUANTITY,
A.TRADE_QUANTITY,
A.NZSO_QUANTITY,
A.EDUCATION_QUANTITY,
A.SCHOOL_ESSENTIALS_QUANTITY,
A.BOOK_FAIR_QUANTITY,
A.NUMBER_BILLED,
A.QUANTITY_RECEIVED_IN_SHIPMENT,
A.QUANTITY_RETURNED,
A.RATE,
A.AMOUNT,
A.ITEM_GROSS_AMOUNT,
A.AMOUNT_FOREIGN,
A.NET_AMOUNT,
A.NET_AMOUNT_FOREIGN,
A.GROSS_AMOUNT,
A.MATCH_BILL_TO_RECEIPT,
A.TRACK_LANDED_COST,
A.TAX_AMOUNT,
A.FREIGHT_RATE,
A.PO_TYPE_KEY,   
A.PO_STATUS_KEY,    
A.APPROVAL_STATUS,
A.CREATION_DATE,
A.LAST_MODIFIED_DATE,  
SYSDATE AS DATE_ACTIVE_FROM,
'9999-12-31 11:59:59' AS DATE_ACTIVE_TO,
1 AS DW_CURRENT
 FROM
 DW_PRESTAGE.PO_FACT_ERROR A
 WHERE 
 RECORD_STATUS = 'INSERT';
 
 /* fact -> UPDATE THE OLD RECORDS SETTING THE CURRENT FLAG VALUE TO 0 */
UPDATE dw.po_fact SET dw_current = 0,DATE_ACTIVE_TO = (sysdate -1) WHERE dw_current = 1
AND   sysdate>= date_active_from
AND   sysdate< date_active_to
AND   EXISTS (SELECT 1 FROM dw_prestage.po_fact_error
  WHERE dw.po_fact.transaction_ID = dw_prestage.po_fact_error.transaction_id
  AND   dw.po_fact.transaction_LINE_ID = dw_prestage.po_fact_error.transaction_line_id
  AND dw.po_fact.subsidiary_KEY = dw_prestage.po_fact_error.subsidiary_key
  AND dw_prestage.po_fact_error.RECORD_STATUS = 'PROCESSED');
  
/* fact -> INSERT UPDATED REPROCESSED RECORDS WHICH HAVE ALL VALID DIMENSIONS*/
INSERT INTO dw.po_fact
(
PO_NUMBER,
  PO_ID,
  PO_LINE_ID,
  REF_TRX_NUMBER,
  REF_TRX_TYPE_KEY, 
  VENDOR_KEY,
  REQUESTER_KEY,
  APPROVER_LEVEL1_KEY,
  APPROVER_LEVEL2_KEY,
  CREATE_DATE_KEY,
  SUBSIDIARY_KEY,
  LOCATION_KEY,
  COST_CENTER_KEY,
  ITEM_KEY,
  REQUESTED_RECEIPT_DATE_KEY,
  ACTUAL_DELIVERY_DATE_KEY,
  FREIGHT_ESTIMATE_METHOD_KEY,
  TERMS_KEY,
  TAX_ITEM_KEY,
  CURRENCY_KEY,
  CLASS_KEY,
  CARRIER_KEY,
  EXCHANGE_RATE,
  BILL_ADDRESS_LINE_1,
  BILL_ADDRESS_LINE_2,
  BILL_ADDRESS_LINE_3,
  BILL_CITY,
  BILL_COUNTRY,
  BILL_STATE,
  BILL_ZIP,
  SHIP_ADDRESS_LINE_1,
  SHIP_ADDRESS_LINE_2,
  SHIP_ADDRESS_LINE_3,
  SHIP_CITY,
  SHIP_COUNTRY,
  SHIP_STATE,
  SHIP_ZIP,
  QUANTITY,
  BIH_QUANTITY,
  BC_QUANTITY,
  TRADE_QUANTITY,
  NZSO_QUANTITY,
  EDUCATION_QUANTITY,
  SCHOOL_ESSENTIALS_QUANTITY,
  BOOK_FAIR_QUANTITY,
  NUMBER_BILLED,
  QUANTITY_RECEIVED_IN_SHIPMENT,
  QUANTITY_RETURNED,
  RATE,
  AMOUNT,
  ITEM_GROSS_AMOUNT,
  AMOUNT_FOREIGN,
  NET_AMOUNT,
  NET_AMOUNT_FOREIGN,
  GROSS_AMOUNT,
  MATCH_BILL_TO_RECEIPT,
  TRACK_LANDED_COST,
  TAX_AMOUNT,
  FREIGHT_RATE,
  PO_TYPE_KEY,   
  PO_STATUS_KEY,    
  APPROVAL_STATUS,
  CREATION_DATE,
  LAST_MODIFIED_DATE,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_CURRENT
)
SELECT
 A.PO_NUMBER,
A.PO_ID,
A.PO_LINE_ID,
A.REF_TRX_NUMBER,
A.REF_TRX_TYPE_KEY, 
A.VENDOR_KEY,
A.REQUESTER_KEY,
A.APPROVER_LEVEL1_KEY,
A.APPROVER_LEVEL2_KEY,
A.CREATE_DATE_KEY,
A.SUBSIDIARY_KEY,
A.LOCATION_KEY,
A.COST_CENTER_KEY,
A.ITEM_KEY,
A.REQUESTED_RECEIPT_DATE_KEY,
A.ACTUAL_DELIVERY_DATE_KEY,
A.FREIGHT_ESTIMATE_METHOD_KEY,
A.TERMS_KEY,
A.TAX_ITEM_KEY,
A.CURRENCY_KEY,
A.CLASS_KEY,
A.CARRIER_KEY,
A.EXCHANGE_RATE,
A.BILL_ADDRESS_LINE_1,
A.BILL_ADDRESS_LINE_2,
A.BILL_ADDRESS_LINE_3,
A.BILL_CITY,
A.BILL_COUNTRY,
A.BILL_STATE,
A.BILL_ZIP,
A.SHIP_ADDRESS_LINE_1,
A.SHIP_ADDRESS_LINE_2,
A.SHIP_ADDRESS_LINE_3,
A.SHIP_CITY,
A.SHIP_COUNTRY,
A.SHIP_STATE,
A.SHIP_ZIP,
A.QUANTITY,
A.BIH_QUANTITY,
A.BC_QUANTITY,
A.TRADE_QUANTITY,
A.NZSO_QUANTITY,
A.EDUCATION_QUANTITY,
A.SCHOOL_ESSENTIALS_QUANTITY,
A.BOOK_FAIR_QUANTITY,
A.NUMBER_BILLED,
A.QUANTITY_RECEIVED_IN_SHIPMENT,
A.QUANTITY_RETURNED,
A.RATE,
A.AMOUNT,
A.ITEM_GROSS_AMOUNT,
A.AMOUNT_FOREIGN,
A.NET_AMOUNT,
A.NET_AMOUNT_FOREIGN,
A.GROSS_AMOUNT,
A.MATCH_BILL_TO_RECEIPT,
A.TRACK_LANDED_COST,
A.TAX_AMOUNT,
A.FREIGHT_RATE,
A.PO_TYPE_KEY,   
A.PO_STATUS_KEY,    
A.APPROVAL_STATUS,
A.CREATION_DATE,
A.LAST_MODIFIED_DATE,  
SYSDATE AS DATE_ACTIVE_FROM,
'9999-12-31 11:59:59' AS DATE_ACTIVE_TO,
1 AS DW_CURRENT
 FROM
 DW_PRESTAGE.PO_FACT_ERROR A
 WHERE 
 RECORD_STATUS = 'PROCESSED';
 
/* fact -> UPDATE THE ERROR TABLE TO SET THE SATUS AS PROCESSED */
UPDATE dw.po_fact_error SET RECORD_STATUS = 'PROCESSED'
where exists ( select 1 from dw_prestage.po_fact_error b
  WHERE dw.po_fact_error.RUNID = b.RUNID
  AND dw.po_fact_error.transaction_id = b.transaction_id
  AND dw.po_fact_error.transaction_line_id = b.transaction_line_id);