CREATE TABLE dw.dwdate
(
DATE_KEY	                BIGINT IDENTITY(0,1)
,DATE_ID	                INTEGER
,DAY_OF_YEAR_NUMBER        	INTEGER
,DAY_NAME                  	VARCHAR(10)
,WEEK_NUMBER               	INTEGER
,WEEK_ENDING               	DATE
,CALENDAR_MONTH_BEGIN      	DATE
,CALENDAR_MONTH_END        	DATE
,CALENDAR_YEAR             	INTEGER
,MONTH_DAY_NUMBER          	INTEGER
,MONTH_NAME                	VARCHAR(10)
,MONTH_NUMBER              	INTEGER
,QUARTER_NUMBER            	INTEGER
,FISCAL_DAY_OF_YEAR_NUMBER 	INTEGER
,FISCAL_WEEK_NUMBER        	INTEGER
,FISCAL_QUARTER_NUMBER     	INTEGER
,FISCAL_MONTH_BEGIN        	DATE
,FISCAL_MONTH_END          	DATE
,FISCAL_YEAR               	INTEGER
,HOLIDAY_IND               	VARCHAR(1)
,FISCAL_YEAR_BEGIN_DATE    	DATE
,FISCAL_YEAR_END_DATE      	DATE
,FISCAL_YEAR_MONTH_DESC    	VARCHAR(20)
,CALENDAR_YEAR_MONTH_DESC   	VARCHAR(20)
,FISCAL_YEAR_MONTH_NBR     	INTEGER
,CALENDAR_YEAR_MONTH_NBR   	INTEGER 
,PRIMARY KEY ( DATE_KEY , DATE_ID) )
DISTSTYLE ALL
INTERLEAVED SORTKEY (DATE_KEY , DATE_ID );

