CREATE SCHEMA if not exists dw;

DROP TABLE if exists dw.item_group;

CREATE TABLE dw.item_group 
(
  ITEM_GROUP_KEY       BIGINT IDENTITY(0,1),
  ITEM_GROUP_ID        INTEGER,
  BOM_QUANTITY         DECIMAL(12,5),
  COMPONENT_YIELD      DECIMAL(22,0),
  EFFECTIVE_DATE       TIMESTAMP,
  EFFECTIVE_REVISION   DECIMAL(22,0),
  LINE_ID              INTEGER,
  MEMBER_ID            INTEGER,
  MEMBER_KEY           INTEGER,
  OBSOLETE_DATE        TIMESTAMP,
  OBSOLETE_REVISION    DECIMAL(22,0),
  PARENT_ID            INTEGER,
  PARENT_KEY           INTEGER,
  QUANTITY             DECIMAL(12,5),
  RATE_PLAN_ID         INTEGER,
  DATE_ACTIVE_FROM     TIMESTAMP,
  DATE_ACTIVE_TO       TIMESTAMP,
  DW_ACTIVE            VARCHAR(1),
  PRIMARY KEY (ITEM_GROUP_KEY)
)
DISTSTYLE ALL INTERLEAVED SORTKEY (PARENT_KEY,MEMBER_KEY);

