CREATE SCHEMA if not exists dw_stage;

DROP TABLE if exists dw_stage.item_group;

CREATE TABLE dw_stage.item_group 
(
  ITEM_GROUP_ID        INTEGER,
  BOM_QUANTITY         DECIMAL(12,5),
  COMPONENT_YIELD      DECIMAL(22,0),
  EFFECTIVE_DATE       TIMESTAMP,
  EFFECTIVE_REVISION   DECIMAL(22,0),
  LINE_ID              INTEGER,
  MEMBER_ID            INTEGER,
  OBSOLETE_DATE        TIMESTAMP,
  OBSOLETE_REVISION    DECIMAL(22,0),
  PARENT_ID            INTEGER,
  QUANTITY             DECIMAL(12,5),
  RATE_PLAN_ID         INTEGER,
  PRIMARY KEY (ITEM_GROUP_ID)
)
DISTSTYLE ALL INTERLEAVED SORTKEY (ITEM_GROUP_ID);

