CREATE SCHEMA if not exists dw;

DROP TABLE if exists dw.payment_terms;

CREATE TABLE dw.payment_terms 
(
  PAYMENT_TERM_KEY      BIGINT IDENTITY(0,1),
  PAYMENT_TERMS_ID       INTEGER,
  NAME                  VARCHAR(83),
  PAYMENT_TERMS_EXTID   VARCHAR(500),
  PERCENTAGE_DISCOUNT   DECIMAL(10,5),
  MINIMUM_DAYS          DECIMAL(22,0),
  IS_PREFERRED          VARCHAR(10),
  ISINACTIVE            VARCHAR(10),
  DISCOUNT_DAYS         DECIMAL(22,0),
  DAYS_UNTIL_DUE        DECIMAL(22,0),
  DATE_DRIVEN           VARCHAR(10),
  DATE_ACTIVE_FROM      TIMESTAMP,
  DATE_ACTIVE_TO        TIMESTAMP,
  DW_ACTIVE             VARCHAR(1),
  PRIMARY KEY (PAYMENT_TERM_KEY,PAYMENT_TERMS_ID)
)
DISTSTYLE ALL INTERLEAVED SORTKEY (PAYMENT_TERM_KEY,PAYMENT_TERMS_ID);

INSERT INTO dw.payment_terms
(
  PAYMENT_TERMS_ID,
  NAME,
  PAYMENT_TERMS_EXTID,
  PERCENTAGE_DISCOUNT,
  MINIMUM_DAYS,
  IS_PREFERRED,
  ISINACTIVE,
  DISCOUNT_DAYS,
  DAYS_UNTIL_DUE,
  DATE_DRIVEN,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE
)
SELECT -99 AS PAYMENT_TERMS_ID,
       'NA_GDW' AS NAME,
       'NA_GDW' AS PAYMENT_TERMS_EXTID,
       -99 AS PERCENTAGE_DISCOUNT,
       -99 AS MINIMUM_DAYS,
       'NA_GDW' AS IS_PREFERRED,
       'NA_GDW' AS ISINACTIVE,
       -99 AS DISCOUNT_DAYS,
       -99 AS DAYS_UNTIL_DUE,
       'NA_GDW' AS DATE_DRIVEN,
       sysdate AS DATE_ACTIVE_FROM,
       '9999-12-31 23:59:59' AS DATE_ACTIVE_TO,
       'A' AS DW_ACTIVE;

INSERT INTO dw.payment_terms
(
  PAYMENT_TERMS_ID,
  NAME,
  PAYMENT_TERMS_EXTID,
  PERCENTAGE_DISCOUNT,
  MINIMUM_DAYS,
  IS_PREFERRED,
  ISINACTIVE,
  DISCOUNT_DAYS,
  DAYS_UNTIL_DUE,
  DATE_DRIVEN,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE
)
SELECT 0 AS PAYMENT_TERMS_ID,
       'NA_ERR' AS NAME,
       'NA_ERR' AS PAYMENT_TERMS_EXTID,
       0 AS PERCENTAGE_DISCOUNT,
       0 AS MINIMUM_DAYS,
       'NA_ERR' AS IS_PREFERRED,
       'NA_ERR' AS ISINACTIVE,
       0 AS DISCOUNT_DAYS,
       0 AS DAYS_UNTIL_DUE,
       'NA_ERR' AS DATE_DRIVEN,
       sysdate AS DATE_ACTIVE_FROM,
       '9999-12-31 23:59:59' AS DATE_ACTIVE_TO,
       'A' AS DW_ACTIVE;

COMMIT;

