SELECT 1 as runid,
       DATE_DRIVEN,
       TO_CHAR(PAYMENT_TERMS.DATE_LAST_MODIFIED,'YYYY-MM-DD HH24:MI:SS') AS DATE_LAST_MODIFIED,
       DAYS_UNTIL_DUE,
       DISCOUNT_DAYS,
       ISINACTIVE,
       IS_PREFERRED,
       MINIMUM_DAYS,
       NAME,
       REPLACE(REPLACE(PAYMENT_TERMS.PAYMENT_TERMS_EXTID,CHR(10),' '),CHR(13),' ') AS PAYMENT_TERMS_EXTID,
       TO_CHAR(PAYMENT_TERMS.PAYMENT_TERMS_ID) AS PAYMENT_TERMS_ID,
       PERCENTAGE_DISCOUNT
FROM PAYMENT_TERMS
WHERE PAYMENT_TERMS.DATE_LAST_MODIFIED > '1900-01-01 00:00:00';
