SELECT PRODUCT_CATALOGUE_ID,
       CLASS_ID,
       SUBSIDIARY_ID,
       LOCATION_ID,
       PUBLISHER_ID,
       PARENT_ID,
       CASE
         WHEN PARENT_ID = COMPONENT_ID THEN NULL
         ELSE COMPONENT_ID
       END COMPONENT_ID,
       PREPACK_QTY,
       ON_HAND_COUNT QTY_ON_HAND,
       ON_ORDER_COUNT QTY_ON_ORDER,
       QUANTITYBACKORDERED QTY_BACKORDERED
FROM (SELECT A.PRODUCT_CATALOGUE_ID,
             F.CLASS_ID,
             E.SUBSIDIARY_ID,
             I.LOCATION_ID,
             H.PUBLISHER_ID,
             G.ITEM_ID PARENT_ID,
             H.ITEM_ID COMPONENT_ID,
             NULL AS PREPACK_QTY,
             J.ON_HAND_COUNT,
             J.ON_ORDER_COUNT,
             J.QUANTITYBACKORDERED
      FROM product_catalogue a
        INNER JOIN ISSUEOFFERMONTH c ON (a.ISSUEOFFERMONTH_ID = c.ISSUEOFFERMONTH_ID)
        INNER JOIN PRODUCT_CATALOGUE_YEAR d ON (a.YEAR_ID = d.PRODUCT_CATALOGUE_YEAR_ID)
        INNER JOIN SUBSIDIARIES E ON (A.SUBSIDIARY_ID = E.SUBSIDIARY_ID)
        INNER JOIN CLASSES F ON (A.LINE_OF_BUSINESS_ID = F.CLASS_ID)
        INNER JOIN PRODUCT_CATALOGUE_MAP G ON (A.PRODUCT_CATALOGUE_ID = G.PRODUCT_CATALOGUE_ID)
        INNER JOIN ITEMS H ON (G.ITEM_ID = H.ITEM_ID)
        INNER JOIN SUBSIDIARY_LOCATION_MAP I ON (I.SUBSIDIARY_ID = E.SUBSIDIARY_ID)
        INNER JOIN ITEM_LOCATION_MAP J
                ON (J.LOCATION_ID = I.LOCATION_ID
               AND J.ITEM_ID = H.ITEM_ID)
      WHERE a.IS_INACTIVE = 'F'
      AND   f.name IN ('Book Clubs' ,'Books in Home' )
      AND   E.SUBSIDIARY_ID = '%s'
      AND   d.PRODUCT_CATALOGUE_YEAR_NAME = to_char (to_timestamp ('%s','YYYY-MM-DD HH24:MI:SS'),'YYYY')
      UNION ALL
      SELECT A.PRODUCT_CATALOGUE_ID,
             F.CLASS_ID,
             E.SUBSIDIARY_ID,
             J.LOCATION_ID,
             I.PUBLISHER_ID,
             G.ITEM_ID PARENT_ID,
             I.ITEM_ID COMPONENT_ID,
             H.QUANTITY PREPACK_QTY,
             K.ON_HAND_COUNT,
             K.ON_ORDER_COUNT,
             K.QUANTITYBACKORDERED
      FROM product_catalogue a
        INNER JOIN ISSUEOFFERMONTH c ON (a.ISSUEOFFERMONTH_ID = c.ISSUEOFFERMONTH_ID)
        INNER JOIN PRODUCT_CATALOGUE_YEAR d ON (a.YEAR_ID = d.PRODUCT_CATALOGUE_YEAR_ID)
        INNER JOIN SUBSIDIARIES E ON (A.SUBSIDIARY_ID = E.SUBSIDIARY_ID)
        INNER JOIN CLASSES F ON (A.LINE_OF_BUSINESS_ID = F.CLASS_ID)
        INNER JOIN PRODUCT_CATALOGUE_MAP G ON (A.PRODUCT_CATALOGUE_ID = G.PRODUCT_CATALOGUE_ID)
        INNER JOIN ITEM_GROUP H ON (G.ITEM_ID = H.PARENT_ID)
        INNER JOIN ITEMS I ON (H.MEMBER_ID = I.ITEM_ID)
        INNER JOIN SUBSIDIARY_LOCATION_MAP J ON (J.SUBSIDIARY_ID = E.SUBSIDIARY_ID)
        INNER JOIN ITEM_LOCATION_MAP K
                ON (K.LOCATION_ID = J.LOCATION_ID
               AND K.ITEM_ID = I.ITEM_ID)
      WHERE a.IS_INACTIVE = 'F'
      AND   f.name IN ('Book Clubs','Books in Home')
      AND   E.SUBSIDIARY_ID = '%s'
      AND   d.PRODUCT_CATALOGUE_YEAR_NAME = to_char (to_timestamp ('%s','YYYY-MM-DD HH24:MI:SS'),'YYYY'))
ORDER BY SUBSIDIARY_ID,
         CLASS_ID,
         LOCATION_ID,
         PRODUCT_CATALOGUE_ID,
         PARENT_ID,
         COMPONENT_ID DESC,
         PREPACK_QTY;