SELECT TO_CHAR(A.SUBSIDIARY_ID) SUBSIDIARY_ID,
       TO_CHAR(B.LOCATION_ID) LOCATION_ID,
       TO_CHAR(B.ITEM_ID) ITEM_ID,
       B.AVERAGE_COST AVG_COST,
       B.AVAILABLE_COUNT QTY_AVAILABLE,
       B.ON_HAND_COUNT QTY_ON_HAND,
       B.ON_ORDER_COUNT QTY_ON_ORDER,
       B.QUANTITYBACKORDERED QTY_BACKORDERED
FROM SUBSIDIARY_LOCATION_MAP A,
     ITEM_LOCATION_MAP B
WHERE A.SUBSIDIARY_ID = '%s'
AND   B.LOCATION_ID = A.LOCATION_ID
AND   B.A1W_DOWNLOAD_TIME_STAMP IS NOT NULL
AND   B.A1W_DOWNLOAD_TIME_STAMP >= to_timestamp ('%s','YYYY-MM-DD HH24:MI:SS')
ORDER BY A.SUBSIDIARY_ID ,B.LOCATION_ID ,B.ITEM_ID;