/* prestage - drop intermediate insert table */
DROP TABLE if exists dw_prestage.vb_fact_insert;

/* prestage - create intermediate insert table*/
CREATE TABLE dw_prestage.vb_fact_insert 
AS
SELECT *
FROM dw_prestage.vb_fact
WHERE EXISTS (SELECT 1
FROM (SELECT TRANSACTION_ID, transaction_line_id FROM (SELECT TRANSACTION_ID, transaction_line_id FROM dw_prestage.vb_fact MINUS SELECT TRANSACTION_ID, transaction_line_id FROM dw_stage.vb_fact)) a
WHERE dw_prestage.vb_fact.TRANSACTION_ID = a.TRANSACTION_ID
AND   dw_prestage.vb_fact.transaction_line_id = a.transaction_line_id
);

/* prestage - drop intermediate update table*/
DROP TABLE if exists dw_prestage.vb_fact_update;

/* prestage - create intermediate update table*/
CREATE TABLE dw_prestage.vb_fact_update 
AS
SELECT TRANSACTION_ID,
       transaction_line_id
FROM (SELECT TRANSACTION_ID,
             transaction_line_id
      FROM (SELECT TRANSACTION_ID
                  ,TRANSACTION_LINE_ID
                  ,VB_NUMBER
                  ,VENDOR_ID
                  ,REF_TRX_NUMBER
                  ,REF_TRX_TYPE
                  ,ACCOUNT_NUMBER
                  ,PAYMENT_TERMS_ID
                  ,PAYMENT_HOLD
                  ,VB_DUE_DATE
                  ,GL_POST_DATE
                  ,VENDOR_BILL_DATE
                  ,APPROVER_LEVEL_ONE_ID
                  ,APPROVER_LEVEL_TWO_ID
                  ,REQUESTOR_ID
                  ,SUBSIDIARY_ID
                  ,DEPARTMENT_ID
                  ,ITEM_ID
                  ,LOCATION_ID
                  ,EXCHANGE_RATE
                  ,VENDOR_ADDRESS_LINE_1
                  ,VENDOR_ADDRESS_LINE_2
                  ,VENDOR_ADDRESS_LINE_3
                  ,VENDOR_CITY
                  ,VENDOR_COUNTRY
                  ,VENDOR_STATE
                  ,VENDOR_ZIP
                  ,VB_STATUS
                  ,APPROVAL_STATUS
                  ,ITEM_COUNT
                  ,ITEM_GROSS_AMOUNT
                  ,AMOUNT
                  ,AMOUNT_FOREIGN
                  ,NET_AMOUNT
                  ,NET_AMOUNT_FOREIGN
                  ,GROSS_AMOUNT
                  ,ITEM_UNIT_PRICE
                  ,CLOSE_DATE
                  ,TAX_ITEM_ID
                  ,TAX_AMOUNT
                  ,TAX_AMOUNT_FOREIGN
                  ,VB_TYPE
                  ,CURRENCY_ID
                  ,CLASS_ID
                  ,MATCH_EXCEPTION
                  ,EXCEPTION_MESSAGE
            FROM dw_prestage.vb_fact
            MINUS
            SELECT  TRANSACTION_ID
                  ,TRANSACTION_LINE_ID
                  ,VB_NUMBER
                  ,VENDOR_ID
                  ,REF_TRX_NUMBER
                  ,REF_TRX_TYPE
                  ,ACCOUNT_NUMBER
                  ,PAYMENT_TERMS_ID
                  ,PAYMENT_HOLD
                  ,VB_DUE_DATE
                  ,GL_POST_DATE
                  ,VENDOR_BILL_DATE
                  ,APPROVER_LEVEL_ONE_ID
                  ,APPROVER_LEVEL_TWO_ID
                  ,REQUESTOR_ID
                  ,SUBSIDIARY_ID
                  ,DEPARTMENT_ID
                  ,ITEM_ID
                  ,LOCATION_ID
                  ,EXCHANGE_RATE
                  ,VENDOR_ADDRESS_LINE_1
                  ,VENDOR_ADDRESS_LINE_2
                  ,VENDOR_ADDRESS_LINE_3
                  ,VENDOR_CITY
                  ,VENDOR_COUNTRY
                  ,VENDOR_STATE
                  ,VENDOR_ZIP
                  ,VB_STATUS
                  ,APPROVAL_STATUS
                  ,ITEM_COUNT
                  ,ITEM_GROSS_AMOUNT
                  ,AMOUNT
                  ,AMOUNT_FOREIGN
                  ,NET_AMOUNT
                  ,NET_AMOUNT_FOREIGN
                  ,GROSS_AMOUNT
                  ,ITEM_UNIT_PRICE
                  ,CLOSE_DATE
                  ,TAX_ITEM_ID
                  ,TAX_AMOUNT
                  ,TAX_AMOUNT_FOREIGN
                  ,VB_TYPE
                  ,CURRENCY_ID
                  ,CLASS_ID
                  ,MATCH_EXCEPTION
                  ,EXCEPTION_MESSAGE
            FROM dw_stage.vb_fact)) a
WHERE NOT EXISTS (SELECT 1 FROM dw_prestage.vb_fact_insert WHERE dw_prestage.vb_fact_insert.TRANSACTION_ID = a.TRANSACTION_ID AND   dw_prestage.vb_fact_insert.transaction_line_id = a.transaction_line_id);

/* prestage - drop intermediate no change track table*/
DROP TABLE if exists dw_prestage.vb_fact_nochange;

/* prestage - create intermediate no change track table*/
CREATE TABLE dw_prestage.vb_fact_nochange 
AS
SELECT TRANSACTION_ID,
       transaction_line_id
FROM (SELECT TRANSACTION_ID,
             transaction_line_id
      FROM dw_prestage.vb_fact
      MINUS
      (SELECT TRANSACTION_ID,
             transaction_line_id
      FROM dw_prestage.vb_fact_insert
      UNION ALL
      SELECT TRANSACTION_ID,
             transaction_line_id
      FROM dw_prestage.vb_fact_update));

/* prestage-> stage*/
SELECT 'no of vb fact records ingested in staging -->' ||count(1)
FROM dw_prestage.vb_fact;

/* prestage-> stage*/
SELECT 'no of vb fact records identified to inserted -->' ||count(1)
FROM dw_prestage.vb_fact_insert;

/* prestage-> stage*/
SELECT 'no of vb fact records identified to updated -->' ||count(1)
FROM dw_prestage.vb_fact_update;

/* prestage-> stage*/
SELECT 'no of vb fact records identified as no change -->' ||count(1)
FROM dw_prestage.vb_fact_nochange;

--D --A = B + C + D
/* stage -> delete from stage records to be updated */ 
DELETE
FROM dw_stage.vb_fact USING dw_prestage.vb_fact_update
WHERE dw_stage.vb_fact.transaction_id = dw_prestage.vb_fact_update.transaction_id
AND   dw_stage.vb_fact.transaction_line_id = dw_prestage.vb_fact_update.transaction_line_id;

/* stage -> insert into stage records which have been created */ 
INSERT INTO dw_stage.vb_fact
SELECT *
FROM dw_prestage.vb_fact_insert;

/* stage -> insert into stage records which have been updated */ 
INSERT INTO dw_stage.vb_fact
SELECT *
FROM dw_prestage.vb_fact
WHERE EXISTS (SELECT 1
              FROM dw_prestage.vb_fact_update
              WHERE dw_prestage.vb_fact_update.transaction_id = dw_prestage.vb_fact.transaction_id
              AND   dw_prestage.vb_fact_update.transaction_line_id = dw_prestage.vb_fact.transaction_line_id);

COMMIT;

/* fact -> INSERT NEW RECORDS WHICH HAS ALL VALID DIMENSIONS */ 
INSERT INTO dw.vb_fact
(
  VB_NUMBER                  
  ,VB_ID                      
  ,VB_LINE_ID                 
  ,VENDOR_KEY                 
  ,SOURCE_TRANSACTION_NUMBER  
  ,SOURCE_TRANSACTION_TYPE    
  ,TERMS_KEY                  
  ,DUE_DATE_KEY               
  ,CREATE_DATE_KEY            
  ,ACCOUNT_KEY                
  ,PAYMENT_HOLD               
  ,GL_POST_DATE_KEY           
  ,VENDOR_BILL_DATE_KEY       
  ,REQUESTER_KEY              
  ,APPROVER_LEVEL1_KEY        
  ,APPROVER_LEVEL2_KEY        
  ,SUBSIDIARY_KEY             
  ,LOCATION_KEY               
  ,ITEM_KEY                   
  ,COST_CENTER_KEY            
  ,EXCHANGE_RATE              
  ,VENDOR_ADDRESS_LINE_1      
  ,VENDOR_ADDRESS_LINE_2      
  ,VENDOR_ADDRESS_LINE_3      
  ,VENDOR_CITY                
  ,VENDOR_COUNTRY             
  ,VENDOR_STATE               
  ,VENDOR_ZIP                 
  ,STATUS                     
  ,APPROVAL_STATUS            
  ,QUANTITY                   
  ,ITEM_GROSS_AMOUNT          
  ,AMOUNT                     
  ,AMOUNT_FOREIGN             
  ,NET_AMOUNT                 
  ,NET_AMOUNT_FOREIGN         
  ,GROSS_AMOUNT               
  ,RATE                       
  ,CLOSE_DATE_KEY             
  ,TAX_ITEM_KEY               
  ,TAX_AMOUNT                 
  ,TAX_AMOUNT_FOREIGN         
  ,VB_TYPE                    
  ,CURRENCY_KEY               
  ,CLASS_KEY                  
  ,MATCH_EXCEPTION            
  ,EXCEPTION_MESSAGE          
  ,CREATION_DATE              
  ,LAST_MODIFIED_DATE         
  ,DATE_ACTIVE_FROM           
  ,DATE_ACTIVE_TO             
  ,DW_CURRENT                 
)
SELECT A.vb_number AS vb_number,
       A.TRANSACTION_ID as VB_ID,
       A.TRANSACTION_LINE_ID as VB_LINE_ID,
       B.VENDOR_KEY AS VENDOR_KEY,
       A.REF_TRX_NUMBER AS SOURCE_TRANSACTION_NUMBER
       A.REF_TRX_TYPE AS SOURCE_TRANSACTION_TYPE
       P.PAYMENT_TERM_KEY AS TERMS_KEY,
       
       
       
       C.EMPLOYEE_KEY AS REQUESTER_KEY,
       D.EMPLOYEE_KEY AS APPROVER_LEVEL1_KEY,
       D1.EMPLOYEE_KEY AS APPROVER_LEVEL2_KEY,
       F.DATE_KEY AS CREATE_DATE_KEY,
       G.SUBSIDIARY_KEY AS SUBSIDIARY_KEY,
       L.LOCATION_KEY AS LOCATION_KEY,
       R.DEPARTMENT_KEY AS COST_CENTER_KEY,
       M.ITEM_KEY AS ITEM_KEY,
       H.DATE_KEY AS REQUESTED_RECEIPT_DATE_KEY,
       I.DATE_KEY AS ACTUAL_DELIVERY_DATE_KEY,
       J.FREIGHT_KEY AS FREIGHT_ESTIMATE_METHOD_KEY,
       
       Q.TAX_ITEM_KEY AS TAX_ITEM_KEY,
       K.CURRENCY_KEY AS CURRENCY_KEY,
       S.CLASS_KEY AS CLASS_KEY,
       A.EXCHANGE_RATE AS EXCHANGE_RATE,
       A.BILLADDRESS AS BILLADDRESS,
       A.SHIPADDRESS AS SHIPADDRESS,
       A.ITEM_COUNT AS QUANTITY,
       A.BIH_QUANTITY AS BIH_QUANTITY,
       A.BC_QUANTITY AS BC_QUANTITY,
       A.TRADE_QUANTITY AS TRADE_QUANTITY,
       A.NZSO_QUANTITY AS NZSO_QUANTITY,
       A.EDUCATION_QUANTITY AS EDUCATION_QUANTITY,
       A.SCHOOL_ESSENTIALS_QUANTITY AS SCHOOL_ESSENTIALS_QUANTITY,
       A.BOOK_FAIR_QUANTITY AS BOOK_FAIR_QUANTITY,
       A.ITEM_UNIT_PRICE AS RATE,
       A.AMOUNT AS AMOUNT,
       A.ITEM_GROSS_AMOUNT AS ITEM_GROSS_AMOUNT,
       A.AMOUNT_FOREIGN AS AMOUNT_FOREIGN,
       A.NET_AMOUNT AS NET_AMOUNT,
       A.NET_AMOUNT_FOREIGN AS NET_AMOUNT_FOREIGN,
       A.GROSS_AMOUNT AS GROSS_AMOUNT,
       A.MATCH_BILL_TO_RECEIPT as MATCH_BILL_TO_RECEIPT,
       A.TRACK_LANDED_COST as TRACK_LANDED_COST,
       A.TAX_AMOUNT AS TAX_AMOUNT,
       A.FRIGHT_RATE AS FREIGHT_RATE,
       A.PO_TYPE AS PO_TYPE,
       A.PO_STATUS AS STATUS,
       A.APPROVAL_STATUS AS APPROVAL_STATUS,
       A.CREATE_DATE AS CREATION_DATE,
       A.DATE_LAST_MODIFIED AS LAST_MODIFIED_DATE,
       SYSDATE AS DATE_ACTIVE_FROM,
       '9999-12-31 11:59:59' AS DATE_ACTIVE_TO,
       1 AS DW_CURRENT
FROM dw_prestage.vb_fact_insert A
  INNER JOIN DW.VENDORS B ON (NVL (A.VENDOR_ID,-99) = B.VENDOR_ID)  
  INNER JOIN DW.EMPLOYEES C ON (NVL (A.REQUESTOR_ID,-99) = C.EMPLOYEE_ID)  
  INNER JOIN DW.EMPLOYEES D ON (NVL (A.APPROVER_LEVEL_ONE_ID,-99) = D.EMPLOYEE_ID)  
  INNER JOIN DW.EMPLOYEES D1 ON (NVL (A.APPROVER_LEVEL_TWO_ID,-99) = D1.EMPLOYEE_ID)  
  INNER JOIN DW.DWDATE F ON (NVL (TO_CHAR (A.CREATE_DATE,'YYYYMMDD'),'0') = F.DATE_ID)  
  INNER JOIN DW.SUBSIDIARIES G ON (NVL (A.SUBSIDIARY_ID,-99) = G.SUBSIDIARY_ID)  
  INNER JOIN DW.DWDATE H ON (NVL (TO_CHAR (A.EXPECTED_RECEIPT_DATE,'YYYYMMDD'),'0') = H.DATE_ID)  
  INNER JOIN DW.DWDATE I ON (NVL (TO_CHAR (A.ACTUAL_DELIVERY_DATE,'YYYYMMDD'),'0') = I.DATE_ID)  
  INNER JOIN DW.FREIGHT_ESTIMATE J ON (NVL (A.FREIGHT_ESTIMATE_METHOD_ID,-99) = J.LANDED_COST_RULE_MATRIX_NZ_ID)  
  INNER JOIN DW.CURRENCIES K ON (NVL (A.CURRENCY_ID,-99) = K.CURRENCY_ID)
  INNER JOIN DW.LOCATIONS L ON (NVL (A.LOCATION_ID,-99) = L.LOCATION_ID)
  INNER JOIN DW.ITEMS M ON (NVL (A.ITEM_ID,-99) = M.ITEM_ID)
  INNER JOIN DW.PAYMENT_TERMS P ON (NVL (A.PAYMENT_TERMS_ID,-99) = P.PAYMENT_TERMS_ID)
  INNER JOIN DW.TAX_ITEMS Q ON (NVL (A.TAX_ITEM_ID,-99) = Q.ITEM_ID)
  INNER JOIN DW.COST_CENTER R ON (NVL(A.DEPARTMENT_ID,-99) = R.DEPARTMENT_ID)
  INNER JOIN DW.CLASSES S ON (NVL(A.CLASS_ID,-99) = S.CLASS_ID)
  WHERE A.LINE_TYPE = 'VB_LINE';
  
/* fact -> INSERT NEW RECORDS IN ERROR TABLE WHICH DOES NOT HAVE VALID DIMENSIONS */ 
INSERT INTO dw.vb_fact_error
(
  RUNID,
PO_NUMBER,
VENDOR_KEY,
REQUESTER_KEY,
APPROVER_LEVEL1_KEY,
APPROVER_LEVEL2_KEY,
CREATE_DATE_KEY,
SUBSIDIARY_KEY,
LOCATION_KEY,
COST_CENTER_KEY,
EXCHANGE_RATE,
ITEM_KEY,
BILLADDRESS,
SHIPADDRESS,
QUANTITY,
BIH_QUANTITY,
BC_QUANTITY,
TRADE_QUANTITY,
NZSO_QUANTITY,
EDUCATION_QUANTITY,
SCHOOL_ESSENTIALS_QUANTITY,
BOOK_FAIR_QUANTITY,
RATE,
AMOUNT,
ITEM_GROSS_AMOUNT,
AMOUNT_FOREIGN,
NET_AMOUNT,
NET_AMOUNT_FOREIGN,
GROSS_AMOUNT,
MATCH_BILL_TO_RECEIPT,
TRACK_LANDED_COST,
TAX_ITEM_KEY,
TAX_AMOUNT,
REQUESTED_RECEIPT_DATE_KEY,
ACTUAL_DELIVERY_DATE_KEY,
FREIGHT_ESTIMATE_METHOD_KEY,
FREIGHT_RATE,
TERMS_KEY,
PO_TYPE,
STATUS,
APPROVAL_STATUS,
CREATION_DATE,
LAST_MODIFIED_DATE,
CURRENCY_KEY,
CLASS_KEY,
VENDOR_ID,
REQUESTER_ID,
APPROVER_LEVEL1_ID,
APPROVER_LEVEL2_ID,
SUBSIDIARY_ID,
LOCATION_ID,
COST_CENTER_ID,
ITEM_ID,
TAX_ITEM_ID,
REQUESTED_RECEIPT_DATE,
ACTUAL_DELIVERY_DATE,
FREIGHT_ESTIMATE_METHOD_ID,
TERMS_ID,
CURRENCY_ID,
CLASS_ID,
RECORD_STATUS,
DW_CREATION_DATE
)
SELECT 
A.RUNID ,
A.PO_NUMBER,
B.VENDOR_KEY,
C.EMPLOYEE_KEY AS REQUESTER_KEY,
D.EMPLOYEE_KEY AS APPROVER_LEVEL1_KEY,
D.EMPLOYEE_KEY AS APPROVER_LEVEL2_KEY,
F.DATE_KEY AS CREATE_DATE_KEY,
G.SUBSIDIARY_KEY AS SUBSIDIARY_KEY,
L.LOCATION_KEY AS LOCATION_KEY,
R.DEPARTMENT_KEY AS COST_CENTER_KEY,
A.EXCHANGE_RATE,
M.ITEM_KEY AS ITEM_KEY,
A.BILLADDRESS,
A.SHIPADDRESS,
A.ITEM_COUNT AS QUANTITY,
A.BIH_QUANTITY,
A.BC_QUANTITY,
A.TRADE_QUANTITY,
A.NZSO_QUANTITY,
A.EDUCATION_QUANTITY,
A.SCHOOL_ESSENTIALS_QUANTITY,
A.BOOK_FAIR_QUANTITY,
A.ITEM_UNIT_PRICE AS RATE,
A.AMOUNT,
A.ITEM_GROSS_AMOUNT,
A.AMOUNT_FOREIGN,
A.NET_AMOUNT,
A.NET_AMOUNT_FOREIGN,
A.GROSS_AMOUNT,
A.MATCH_BILL_TO_RECEIPT,
A.TRACK_LANDED_COST,
Q.TAX_ITEM_KEY AS TAX_ITEM_KEY,
A.TAX_AMOUNT,
H.DATE_KEY AS REQUESTED_RECEIPT_DATE_KEY,
I.DATE_KEY AS ACTUAL_DELIVERY_DATE_KEY,
J.FREIGHT_KEY AS FREIGHT_ESTIMATE_METHOD_KEY,
A.FRIGHT_RATE AS FREIGHT_RATE,
P.PAYMENT_TERM_KEY AS TERMS_KEY,
A.PO_TYPE,
A.PO_STATUS AS STATUS,
A.APPROVAL_STATUS,
A.CREATE_DATE AS CREATION_DATE,
A.DATE_LAST_MODIFIED AS LAST_MODIFIED_DATE,
K.CURRENCY_KEY AS CURRENCY_KEY,
S.CLASS_KEY AS CLASS_KEY ,
A.VENDOR_ID ,
A.REQUESTOR_ID ,
A.APPROVER_LEVEL_ONE_ID ,
A.APPROVER_LEVEL_TWO_ID ,
A.SUBSIDIARY_ID ,
A.LOCATION_ID ,
A.DEPARTMENT_ID AS COST_CENTER_ID,
A.ITEM_ID,
A.TAX_ITEM_ID,
A.EXPECTED_RECEIPT_DATE,
A.ACTUAL_DELIVERY_DATE,
A.FREIGHT_ESTIMATE_METHOD_ID,
A.PAYMENT_TERMS_ID AS TERMS_ID,
A.CURRENCY_ID,
A.CLASS_ID,
'ERROR' AS RECORD_STATUS,
SYSDATE AS DW_CREATION_DATE
FROM dw_prestage.vb_fact_insert A
  LEFT OUTER JOIN DW.VENDORS B ON (NVL (A.VENDOR_ID,0) = B.VENDOR_ID)  
  LEFT OUTER JOIN DW.EMPLOYEES C ON (NVL (A.REQUESTOR_ID,0) = C.EMPLOYEE_ID)  
  LEFT OUTER JOIN DW.EMPLOYEES D ON (NVL (A.APPROVER_LEVEL_ONE_ID,0) = D.EMPLOYEE_ID)  
  LEFT OUTER JOIN DW.EMPLOYEES D1 ON (NVL (A.APPROVER_LEVEL_TWO_ID,0) = D1.EMPLOYEE_ID)  
  LEFT OUTER JOIN DW.DWDATE F ON (NVL (TO_CHAR (A.CREATE_DATE,'YYYYMMDD'),'0') = F.DATE_ID)  
  LEFT OUTER JOIN DW.SUBSIDIARIES G ON (NVL (A.SUBSIDIARY_ID,0) = G.SUBSIDIARY_ID)  
  LEFT OUTER JOIN DW.DWDATE H ON (NVL (TO_CHAR (A.EXPECTED_RECEIPT_DATE,'YYYYMMDD'),'0') = H.DATE_ID)  
  LEFT OUTER JOIN DW.DWDATE I ON (NVL (TO_CHAR (A.ACTUAL_DELIVERY_DATE,'YYYYMMDD'),'0') = I.DATE_ID)  
  LEFT OUTER JOIN DW.FREIGHT_ESTIMATE J ON (NVL (A.FREIGHT_ESTIMATE_METHOD_ID,0) = J.LANDED_COST_RULE_MATRIX_NZ_ID)  
  LEFT OUTER JOIN DW.CURRENCIES K ON (NVL (A.CURRENCY_ID,0) = K.CURRENCY_ID)
  LEFT OUTER JOIN DW.LOCATIONS L ON (NVL (A.LOCATION_ID,0) = L.LOCATION_ID)
  LEFT OUTER JOIN DW.ITEMS M ON (NVL (A.ITEM_ID,0) = M.ITEM_ID)
  LEFT OUTER JOIN DW.PAYMENT_TERMS P ON (NVL (A.PAYMENT_TERMS_ID,0) = P.PAYMENT_TERMS_ID)
  LEFT OUTER JOIN DW.TAX_ITEMS Q ON (NVL (A.TAX_ITEM_ID,0) = Q.ITEM_ID)
  LEFT OUTER JOIN DW.COST_CENTER R ON (NVL(A.DEPARTMENT_ID,0) = R.DEPARTMENT_ID)
  LEFT OUTER JOIN DW.CLASSES S ON (NVL(A.CLASS_ID,0) = S.CLASS_ID)
  WHERE A.LINE_TYPE = 'PO_LINE' AND 
  (B.VENDOR_KEY IS NULL OR
  C.EMPLOYEE_KEY IS NULL OR
  D.EMPLOYEE_KEY IS NULL OR
  D1.EMPLOYEE_KEY IS NULL OR
  F.DATE_KEY IS NULL OR
  G.SUBSIDIARY_KEY IS NULL OR
  L.LOCATION_KEY IS NULL OR
  R.DEPARTMENT_KEY IS NULL OR
  M.ITEM_KEY IS NULL OR
  Q.TAX_ITEM_KEY IS NULL OR
  H.DATE_KEY IS NULL OR
  I.DATE_KEY IS NULL OR
  J.FREIGHT_KEY IS NULL OR
  PAYMENT_TERM_KEY IS NULL OR
  K.CURRENCY_KEY IS NULL OR
  S.CLASS_KEY IS NULL );

/* fact -> UPDATE THE OLD RECORDS SETTING THE CURRENT FLAG VALUE TO 0 */  
UPDATE dw.vb_fact SET dw_current = 0,DATE_ACTIVE_TO = (sysdate -1) WHERE dw_current = 1
AND   sysdate>= date_active_from
AND   sysdate< date_active_to
AND   EXISTS (SELECT 1 FROM dw_prestage.vb_fact_update WHERE dw.vb_fact.transaction_id = dw_prestage.vb_fact_update.transaction_id AND   dw.vb_fact.transaction_line_id = dw_prestage.vb_fact_update.transaction_line_id);

/* fact -> NOW INSERT THE FACT RECORDS WHICH HAVE BEEN UPDATED AT THE SOURCE */ 
INSERT INTO dw.vb_fact
(
  PO_NUMBER,
  VENDOR_KEY  ,
  REQUESTER_KEY  ,
  APPROVER_KEY  ,
  RECEIVE_BY_DATE_KEY ,
  CREATE_DATE_KEY  ,
  SUBSIDIARY_KEY  ,
  LOCATION_KEY  ,
  COST_CENTER_KEY  ,
  ITEM_KEY  ,
  VENDOR_ITEM_KEY  ,
  REQUESTED_RECEIPT_DATE_KEY  ,
  ACTUAL_DELIVERY_DATE_KEY  ,
  FREIGHT_ESTIMATE_METHOD_KEY  ,
  CARRIER_KEY  ,
  TERMS_KEY  ,
  TAX_ITEM_KEY  ,
  CURRENCY_KEY  ,
  EXCHANGE_RATE,
  BILLADDRESS,
  SHIPADDRESS,
  QUANTITY,
  BIH_QUANTITY,
  BC_QUANTITY,
  TRADE_QUANTITY,
  NZSO_QUANTITY,
  EDUCATION_QUANTITY,
  SCHOOL_ESSENTIALS_QUANTITY,
  BOOK_FAIR_QUANTITY,
  RATE,
  ITEM_GROSS_AMOUNT,
  TAX_AMOUNT,
  FREIGHT_RATE,
  PO_TYPE,
  STATUS,
  CREATION_DATE,
  LAST_MODIFIED_DATE,
  VALID_TILL_DATE,
  ACTIVE
)
SELECT A.po_number AS po_number,
       B.VENDOR_KEY AS VENDOR_KEY,
       C.EMPLOYEE_KEY AS REQUESTER_KEY,
       D.EMPLOYEE_KEY AS APPROVER_KEY,
       F.DATE_KEY AS CREATE_DATE_KEY,
       G.SUBSIDIARY_KEY AS SUBSIDIARY_KEY,
       -99 AS LOCATION_KEY,
       -99 AS COST_CENTER_KEY,
       -99 AS ITEM_KEY,
       -99 AS VENDOR_ITEM_KEY,
       H.DATE_KEY AS REQUESTED_RECEIPT_DATE_KEY,
       I.DATE_KEY AS ACTUAL_DELIVERY_DATE_KEY,
       J.FREIGHT_KEY AS FREIGHT_ESTIMATE_METHOD_KEY,
       -99 AS CARRIER_KEY,
       -99 AS TERMS_KEY,
       -99 AS TAX_ITEM_KEY,
       K.CURRENCY_KEY AS CURRENCY_KEY,
       A.EXCHANGE_RATE AS EXCHANGE_RATE,
       A.BILLADDRESS AS BILLADDRESS,
       A.SHIPADDRESS AS SHIPADDRESS,
       A.ITEM_COUNT AS QUANTITY,
       A.BIH_QUANTITY AS BIH_QUANTITY,
       A.BC_QUANTITY AS BC_QUANTITY,
       A.TRADE_QUANTITY AS TRADE_QUANTITY,
       A.NZSO_QUANTITY AS NZSO_QUANTITY,
       A.EDUCATION_QUANTITY AS EDUCATION_QUANTITY,
       A.SCHOOL_ESSENTIALS_QUANTITY AS SCHOOL_ESSENTIALS_QUANTITY,
       A.BOOK_FAIR_QUANTITY AS BOOK_FAIR_QUANTITY,
       A.ITEM_UNIT_PRICE AS RATE,
       A.ITEM_GROSS_AMOUNT AS ITEM_GROSS_AMOUNT,
       A.TAX_AMOUNT AS TAX_AMOUNT,
       A.FRIGHT_RATE AS FREIGHT_RATE,
       A.PO_TYPE AS PO_TYPE,
       A.PO_STATUS AS STATUS,
       A.CREATE_DATE AS CREATION_DATE,
       A.DATE_LAST_MODIFIED AS LAST_MODIFIED_DATE,
       SYSDATE AS DATE_ACTIVE_FROM,
       '9999-12-31 11:59:59' AS DATE_ACTIVE_FROM,
       1 AS DW_CURRENT
FROM dw_prestage.vb_fact A
  INNER JOIN DW.VENDORS B ON (NVL (A.VENDOR_ID,-99) = B.VENDOR_ID)  
  INNER JOIN DW.EMPLOYEES C ON (NVL (A.CREATED_BY_ID,-99) = C.EMPLOYEE_ID)  
  INNER JOIN DW.EMPLOYEES D ON (NVL (A.APPROVER_LEVEL_ONE_ID,-99) = D.EMPLOYEE_ID)  
  INNER JOIN DW.DWDATE F ON (NVL (TO_CHAR (A.CREATE_DATE,'YYYYMMDD'),'0') = F.DATE_ID)  
  INNER JOIN DW.SUBSIDIARIES G ON (NVL (A.SUBSIDIARY_ID,-99) = G.SUBSIDIARY_ID)  
  INNER JOIN DW.DWDATE H ON (NVL (TO_CHAR (A.EXPECTED_RECEIPT_DATE,'YYYYMMDD'),'0') = H.DATE_ID)  
  INNER JOIN DW.DWDATE I ON (NVL (TO_CHAR (A.ACTUAL_DELIVERY_DATE,'YYYYMMDD'),'0') = I.DATE_ID)  
  INNER JOIN DW.FREIGHT_ESTIMATE J ON (NVL (A.FREIGHT_ESTIMATE_METHOD_ID,-99) = J.LANDED_COST_RULE_MATRIX_NZ_ID) 
  INNER JOIN DW.CURRENCIES K ON (NVL (A.CURRENCY_ID,-99) = K.CURRENCY_ID)
WHERE A.LINE_TYPE = 'PO_LINE'
AND   EXISTS (SELECT 1 FROM dw_prestage.vb_fact_update WHERE a.transaction_id = dw_prestage.vb_fact_update.transaction_id AND   a.transaction_line_id = dw_prestage.vb_fact_update.transaction_line_id);

/* fact -> INSERT UPDATED RECORDS IN ERROR TABLE WHICH DOES NOT HAVE VALID DIMENSIONS */ 
INSERT INTO dw.vb_fact_error
(
  PO_NUMBER,
  VENDOR_KEY  ,
  REQUESTER_KEY  ,
  APPROVER_KEY  ,
  RECEIVE_BY_DATE_KEY ,
  CREATE_DATE_KEY  ,
  SUBSIDIARY_KEY  ,
  LOCATION_KEY  ,
  COST_CENTER_KEY  ,
  ITEM_KEY  ,
  VENDOR_ITEM_KEY  ,
  REQUESTED_RECEIPT_DATE_KEY  ,
  ACTUAL_DELIVERY_DATE_KEY  ,
  FREIGHT_ESTIMATE_METHOD_KEY  ,
  CARRIER_KEY  ,
  TERMS_KEY  ,
  TAX_ITEM_KEY  ,
  CURRENCY_KEY  ,
  EXCHANGE_RATE,
  BILLADDRESS,
  SHIPADDRESS,
  QUANTITY,
  BIH_QUANTITY,
  BC_QUANTITY,
  TRADE_QUANTITY,
  NZSO_QUANTITY,
  EDUCATION_QUANTITY,
  SCHOOL_ESSENTIALS_QUANTITY,
  BOOK_FAIR_QUANTITY,
  RATE,
  ITEM_GROSS_AMOUNT,
  TAX_AMOUNT,
  FREIGHT_RATE,
  PO_TYPE,
  STATUS,
  CREATION_DATE,
  LAST_MODIFIED_DATE,
  VALID_TILL_DATE,
  ACTIVE
)
SELECT A.po_number AS po_number,
       B.VENDOR_KEY AS VENDOR_KEY,
       A.VENDOR_ID,
       C.EMPLOYEE_KEY AS REQUESTER_KEY,
       A.CREATED_BY_ID,
       D.EMPLOYEE_KEY AS APPROVER_KEY,
       A.APPROVER_LEVEL_ONE_ID,
       F.DATE_KEY AS CREATE_DATE_KEY,
       A.CREATE_DATE,
       G.SUBSIDIARY_KEY AS SUBSIDIARY_KEY,
       A.SUBSIDIARY_ID,
       -99 AS LOCATION_KEY,
       A.LOCATION_ID,
       -99 AS COST_CENTER_KEY,
       A.DEPARTMENT_ID,
       -99 AS ITEM_KEY,
       A.ITEM_ID,
		H.DATE_KEY AS REQUESTED_RECEIPT_DATE_KEY,
       A.EXPECTED_RECEIPT_DATE,
       I.DATE_KEY AS ACTUAL_DELIVERY_DATE_KEY,
       A.ACTUAL_DELIVERY_DATE,
       J.FREIGHT_KEY AS FREIGHT_ESTIMATE_METHOD_KEY,
       A.FREIGHT_ESTIMATE_METHOD_ID,
       -99 AS CARRIER_KEY,
		-99 AS TERMS_KEY,
		-99 AS TAX_ITEM_KEY,
       A.TAX_ITEM_ID,
       K.CURRENCY_KEY AS CURRENCY_KEY,
       A.CURRENCY_ID,
       A.EXCHANGE_RATE AS EXCHANGE_RATE,
       A.BILLADDRESS AS BILLADDRESS,
       A.SHIPADDRESS AS SHIPADDRESS,
       A.ITEM_COUNT AS QUANTITY,
       A.BIH_QUANTITY AS BIH_QUANTITY,
       A.BC_QUANTITY AS BC_QUANTITY,
       A.TRADE_QUANTITY AS TRADE_QUANTITY,
       A.NZSO_QUANTITY AS NZSO_QUANTITY,
       A.EDUCATION_QUANTITY AS EDUCATION_QUANTITY,
       A.SCHOOL_ESSENTIALS_QUANTITY AS SCHOOL_ESSENTIALS_QUANTITY,
       A.BOOK_FAIR_QUANTITY AS BOOK_FAIR_QUANTITY,
       A.ITEM_UNIT_PRICE AS RATE,
       A.ITEM_GROSS_AMOUNT AS ITEM_GROSS_AMOUNT,
       
		A.FRIGHT_RATE AS FREIGHT_RATE,
       A.PO_TYPE AS PO_TYPE,
       A.PO_STATUS AS STATUS,
       A.CREATE_DATE AS CREATION_DATE,
       A.DATE_LAST_MODIFIED AS LAST_MODIFIED_DATE,
       SYSDATE AS DW_CREATION_DATE,
       'E' AS RECORD_STATUS
FROM dw_prestage.vb_fact A
  LEFT OUTER JOIN DW.VENDORS B ON (NVL (A.VENDOR_ID,-99) = B.VENDOR_ID)  
  LEFT OUTER JOIN DW.EMPLOYEES C ON (NVL (A.CREATED_BY_ID,-99) = C.EMPLOYEE_ID)  
  LEFT OUTER JOIN DW.EMPLOYEES D ON (NVL (A.APPROVER_LEVEL_ONE_ID,-99) = D.EMPLOYEE_ID)  
  LEFT OUTER JOIN DW.DWDATE F ON (NVL (TO_CHAR (A.CREATE_DATE,'YYYYMMDD'),'0') = F.DATE_ID)  
  LEFT OUTER JOIN DW.SUBSIDIARIES G ON (NVL (A.SUBSIDIARY_ID,-99) = G.SUBSIDIARY_ID) 
  LEFT OUTER JOIN DW.DWDATE H ON (NVL (TO_CHAR (A.EXPECTED_RECEIPT_DATE,'YYYYMMDD'),'0') = H.DATE_ID)  
  LEFT OUTER JOIN DW.DWDATE I ON (NVL (TO_CHAR (A.ACTUAL_DELIVERY_DATE,'YYYYMMDD'),'0') = I.DATE_ID)  
  LEFT OUTER JOIN DW.FREIGHT_ESTIMATE J ON (NVL (A.FREIGHT_ESTIMATE_METHOD_ID,-99) = J.LANDED_COST_RULE_MATRIX_NZ_ID)  
  LEFT OUTER JOIN DW.CURRENCIES K ON (NVL (A.CURRENCY_ID,-99) = K.CURRENCY_ID)
WHERE A.LINE_TYPE = 'PO_LINE'
AND   EXISTS (SELECT 1 FROM dw_prestage.vb_fact_update WHERE a.transaction_id = dw_prestage.vb_fact_update.transaction_id AND   a.transaction_line_id = dw_prestage.vb_fact_update.transaction_line_id)
AND   (B.VENDOR_KEY IS NULL OR C.EMPLOYEE_KEY IS NULL OR D.EMPLOYEE_KEY IS NULL OR F.DATE_KEY IS NULL OR G.SUBSIDIARY_KEY IS NULL OR< LOCATION_ID > IS NULL OR< COST CENTER > IS NULL OR< ITEM > IS NULL OR< VENDOR ITEM > IS NULL OR H.DATE_KEY IS NULL OR I.DATE_KEY IS NULL OR J.FREIGHT_KEY IS NULL OR< CARRIER > IS NULL OR< TERMS > IS NULL OR< TAX ITEM > IS NULL OR K.CURRENCY_KEY IS NULL);