SELECT
       to_char(PRODUCT_CATALOGUE_ID) PRODUCT_CATALOGUE_ID,
       a.PRODUCT_CATALOGUE_NAME,
       to_char(a.CLUBLEVELREADING_LEVEL_ID) CLUBLEVELREADING_LEVEL_ID,
       b.CLUBLEVELREADING_LEVEL_NAME,
       TO_CHAR(DATE_CREATED,'YYYY-MM-DD HH24:MI:SS') DATE_CREATED,
       TO_CHAR(IN_MARKET_END_DATE,'YYYY-MM-DD HH24:MI:SS') IN_MARKET_END_DATE,
       TO_CHAR(IN_MARKET_START_DATE,'YYYY-MM-DD HH24:MI:SS') IN_MARKET_START_DATE,
       to_char(ISSUEOFFERMONTH_ID) ISSUEOFFERMONTH_ID,
       c.ISSUEOFFERMONTH_NAME,
       c.DESCRIPTION ISSUEOFFERMONTH_DESC,
       IS_INACTIVE,
       TO_CHAR(LAST_MODIFIED_DATE,'YYYY-MM-DD HH24:MI:SS') LAST_MODIFIED_DATE,
       to_char(LINE_OF_BUSINESS_ID) LINE_OF_BUSINESS_ID,
       F.NAME LINE_OF_BUSINESS,
       to_char(NO__OF_BOOKS_IN_OFFER_BIH_O_ID) NO__OF_BOOKS_IN_OFFER_BIH_O_ID,
       OFFER_DESCRIPTION,
       to_char(SUBSIDIARY_ID) SUBSIDIARY_ID,
       E.NAME SUBSIDIARY,
       YEARMONTH_YYYYMM,
       YEARMONTH_YYYYMM__REMOVE,
       to_char(YEAR_ID) YEAR_ID,
       d.PRODUCT_CATALOGUE_YEAR_NAME PRODUCT_CATALOGUE_YEAR
FROM product_catalogue a
  LEFT OUTER JOIN CLUBLEVELREADING_LEVEL b ON (a.CLUBLEVELREADING_LEVEL_ID = b.CLUBLEVELREADING_LEVEL_ID)
  LEFT OUTER JOIN ISSUEOFFERMONTH c ON (a.ISSUEOFFERMONTH_ID = c.ISSUEOFFERMONTH_ID)
  LEFT OUTER JOIN PRODUCT_CATALOGUE_YEAR d ON (a.YEAR_ID = d.PRODUCT_CATALOGUE_YEAR_ID)
  LEFT OUTER JOIN SUBSIDIARIES E ON (A.SUBSIDIARY_ID = E.SUBSIDIARY_ID)
  LEFT OUTER JOIN CLASSES F
               ON (A.LINE_OF_BUSINESS_ID = F.CLASS_ID)
              where a.IS_INACTIVE = 'F'
ORDER BY a.PRODUCT_CATALOGUE_ID;
