/* prestage - drop intermediate insert table */
drop table if exists dw_prestage.vendors_insert;

/* prestage - create intermediate insert table*/
create table dw_prestage.vendors_insert
as
select * from dw_prestage.vendors
where exists ( select 1 from  
(select vendor_id from 
(select vendor_id from dw_prestage.vendors
minus
select vendor_id from dw_stage.vendors )) a
where  dw_prestage.vendors.vendor_id = a.vendor_id );

/* prestage - drop intermediate update table*/
drop table if exists dw_prestage.vendors_update;

/* prestage - create intermediate update table*/
create table dw_prestage.vendors_update
as
select decode(sum(ch_type),3,2,sum(ch_type)) ch_type ,vendor_id
from
(
SELECT vendor_id , CH_TYPE FROM 
(  
select vendor_id , BILLADDRESS,SHIPADDRESS,ACCOUNTNUMBER,LINE1,LINE2,LINE3,ZIPCODE,CITY,STATE,COUNTRY,COMPANYNAME,CURRENCY_NAME,CURRENCY_ID, '2' CH_TYPE from dw_prestage.vendors
MINUS
select vendor_id , BILLADDRESS,SHIPADDRESS,ACCOUNTNUMBER,LINE1,LINE2,LINE3,ZIPCODE,CITY,STATE,COUNTRY,COMPANYNAME,CURRENCY_NAME,CURRENCY_ID, '2' CH_TYPE from dw_stage.vendors
)
union all
SELECT vendor_id , CH_TYPE FROM 
(  
select vendor_id,VENDOR_EXTID,NAME,EMAIL,FULL_NAME,EFT_BILL_PAYMENT,IS1099ELIGIBLE,ISINACTIVE,IS_PERSON,LINE_OF_BUSINESS,LINE_OF_BUSINESS_ID,SUBSIDIARY_NAME,SUBSIDIARY,VENDOR_TYPE, '1' CH_TYPE from dw_prestage.vendors
MINUS
select vendor_id,VENDOR_EXTID,NAME,EMAIL,FULL_NAME,EFT_BILL_PAYMENT,IS1099ELIGIBLE,ISINACTIVE,IS_PERSON,LINE_OF_BUSINESS,LINE_OF_BUSINESS_ID,SUBSIDIARY_NAME,SUBSIDIARY,VENDOR_TYPE, '1' CH_TYPE from dw_stage.vendors
)
) a where not exists ( select 1 from dw_prestage.vendors_insert
where dw_prestage.vendors_insert.vendor_id = a.vendor_id) group by vendor_id;

/* prestage - drop intermediate delete table*/
drop table if exists dw_prestage.vendors_delete;

/* prestage - create intermediate delete table*/
create table dw_prestage.vendors_delete
as
select * from dw_stage.vendors
where exists ( select 1 from  
(select vendor_id from 
(select vendor_id from dw_stage.vendors
minus
select vendor_id from dw_prestage.vendors )) a
where dw_stage.vendors.vendor_id = a.vendor_id );

/* prestage-> stage*/
select 'no of prestage vendor records identified to inserted -->'||count(1) from  dw_prestage.vendors_insert;

/* prestage-> stage*/
select 'no of prestage vendor records identified to updated -->'||count(1) from  dw_prestage.vendors_update;

/* prestage-> stage*/
select 'no of prestage vendor records identified to deleted -->'||count(1) from  dw_prestage.vendors_delete;

/* stage -> delete from stage records to be updated */
delete from dw_stage.vendors 
using dw_prestage.vendors_update
where dw_stage.vendors.vendor_id = dw_prestage.vendors_update.vendor_id;

/* stage -> delete from stage records which have been deleted */
delete from dw_stage.vendors 
using dw_prestage.vendors_delete
where dw_stage.vendors.vendor_id = dw_prestage.vendors_delete.vendor_id;

/* stage -> insert into stage records which have been created */
insert into dw_stage.vendors (ABCD_MARKER_ID ,ACCOUNTNUMBER ,ACTUAL_COST ,ALTEMAIL ,ALTERNATE_CUSTOMER_EMAIL ,ALTERNATE_CUSTOMER_EMAIL1 ,ALTERNATE_CUSTOMER_EMAIL2 ,ALTPHONE ,APPLY_FREIGHT ,BACKORDERS_ALLOWED ,BACK_ORDER_SPLIT ,BILLADDRESS ,BILLING_CLASS_ID ,BOOK_FAIRS_CONSULTANT_ID ,BOOK_FAIR_ABCD_MARKER ,BOOK_FAIR_SIZE_ID ,BRN ,BUSINESS_STYLE_ID ,CARRIER_ADDRESS ,CARRIER_LABEL_ID ,CITY ,COMMENTS ,COMPANYNAME ,COST_EXPIRED ,COUNTRY ,CREATE_DATE ,CREDITLIMIT ,CTC ,CURRENCY_ID ,CURRENCY_NAME ,CUSTOMER_ID ,DATE_CUSTOMER_STATEMENT_SENT ,DATE_LAST_MODIFIED ,DECILE_ID ,DEFAULT_DISCOUNT_ID ,DEFAULT_DISCOUNT_RATE ,DEFAULT_WT_CODE_ID ,DELIVERY_INSTRUCTION ,DIRECT_DEBIT ,EFT_BILL_PAYMENT ,EFT_CUSTOMER_REFUND_PAYMENT ,EFT_FILE_FORMAT_ID ,ELIGIBLE_FOR_APPROVAL ,EMAIL ,EMAIL_ADDRESS ,EMAIL_ADDRESS_FOR_PAYMENT_NOT ,EMAIL_ADDRESS_FOR_PAYMENT_NO_0 ,EMAIL_FOR_CUSTOMER_STATEMENT ,EMAIL_FOR_CUSTOMER_STATEMENT_ ,EMAIL_FOR_CUSTOMER_STATEMENT_0 ,EMAIL_FOR_CUSTOMER_STATEMENT_1 ,EMPLOYEE_ID ,EXPENSE_ACCOUNT_ID ,FAIR_SIZE ,FAIR_TYPE_ID ,FAX ,FINANCIAL ,FORWARDERS_ADDRESS_ID ,FORWARDER_ADDRESS ,FREIGHT_ESTIMATE_METHOD_ID ,FREIGHT_RATE ,FULL_NAME ,HOME_PHONE ,INCOTERM ,IS1099ELIGIBLE ,ISEMAILHTML ,ISEMAILPDF ,ISINACTIVE ,IS_PERSON ,LABOR_COST ,LAST_MODIFIED_DATE ,LAST_SALES_ACTIVITY ,LEGACY_CUSTOMER_IDCUSTOM ,LINE1 ,LINE2 ,LINE3 ,LINE_OF_BUSINESS_ID ,LINE_OF_BUSINESS ,LOGINACCESS ,LSA_LINK ,LSA_LINK_NAME ,MOBILE_PHONE ,MOE_ID ,NAME ,NO_OF_CHILDREN_ENROLLED ,OLD_CUSTOMER_CODE ,OLD_PARENT_CODE ,OPENBALANCE ,OPENBALANCE_FOREIGN ,OPENING_BALANCE ,PAYABLES_ACCOUNT_ID ,PAYMENT_TERMS_ID ,PHILHEALTH ,PHONE ,PRICE_GROUP_ID ,PRINTONCHECKAS ,PROJECT_SCOPE_STATEMENT ,PROVIDENT_FUND_NUMBER ,PURCHASEORDERAMOUNT ,PURCHASEORDERQUANTITY ,PURCHASEORDERQUANTITYDIFF ,RECEIPTAMOUNT ,RECEIPTQUANTITY ,RECEIPTQUANTITYDIFF ,REGION_ID ,REWARDS_BAND_ID ,REWARD_EARNER_ID ,ROUTE_CODE_ID ,SALES_TERRITORYDO_NOT_USE_ID ,SCHEMAI1L_FOR_INVOICE ,SCHEMAIL_FOR_INVOICE ,SCHOLASTIC_SALES_TERRITORY_ID ,SELLING_RIGHTS_ID ,SHIPADDRESS ,SHIPPING_PREFERENCE_ID ,SNIPP_MEMBER_ID ,SOR_DISCOUNT_ID ,SOR_DURATION_FROM_DAYS ,SOR_DURATION_TO_DAYS ,SOR_TAG ,SOR_THRESHOLD ,SPONSOR ,STAPLES ,STATE ,SUBSIDIARY ,SUBSIDIARY_NAME ,TAXIDNUM ,TAX_CONTACT_FIRST_NAME ,TAX_CONTACT_ID ,TAX_CONTACT_LAST_NAME ,TAX_CONTACT_MIDDLE_NAME ,THIRD_PARTY ,TIN ,TOTAL_QUANTITY ,TRANSACTIONS_NEED_APPROVAL ,UEN ,UK_OTC_CODE ,UNBILLED_ORDERS ,UNBILLED_ORDERS_FOREIGN ,URL ,US_OTC_CODE ,VAT_REGISTRATION_NO ,VENDOR_EXTID ,VENDOR_ID ,VENDOR_TYPE_ID ,VENDOR_TYPE ,ZIPCODE ,ZONE_NUMBER_ID)
select ABCD_MARKER_ID ,ACCOUNTNUMBER ,ACTUAL_COST ,ALTEMAIL ,ALTERNATE_CUSTOMER_EMAIL ,ALTERNATE_CUSTOMER_EMAIL1 ,ALTERNATE_CUSTOMER_EMAIL2 ,ALTPHONE ,APPLY_FREIGHT ,BACKORDERS_ALLOWED ,BACK_ORDER_SPLIT ,BILLADDRESS ,BILLING_CLASS_ID ,BOOK_FAIRS_CONSULTANT_ID ,BOOK_FAIR_ABCD_MARKER ,BOOK_FAIR_SIZE_ID ,BRN ,BUSINESS_STYLE_ID ,CARRIER_ADDRESS ,CARRIER_LABEL_ID ,CITY ,COMMENTS ,COMPANYNAME ,COST_EXPIRED ,COUNTRY ,CREATE_DATE ,CREDITLIMIT ,CTC ,CURRENCY_ID ,CURRENCY_NAME ,CUSTOMER_ID ,DATE_CUSTOMER_STATEMENT_SENT ,DATE_LAST_MODIFIED ,DECILE_ID ,DEFAULT_DISCOUNT_ID ,DEFAULT_DISCOUNT_RATE ,DEFAULT_WT_CODE_ID ,DELIVERY_INSTRUCTION ,DIRECT_DEBIT ,EFT_BILL_PAYMENT ,EFT_CUSTOMER_REFUND_PAYMENT ,EFT_FILE_FORMAT_ID ,ELIGIBLE_FOR_APPROVAL ,EMAIL ,EMAIL_ADDRESS ,EMAIL_ADDRESS_FOR_PAYMENT_NOT ,EMAIL_ADDRESS_FOR_PAYMENT_NO_0 ,EMAIL_FOR_CUSTOMER_STATEMENT ,EMAIL_FOR_CUSTOMER_STATEMENT_ ,EMAIL_FOR_CUSTOMER_STATEMENT_0 ,EMAIL_FOR_CUSTOMER_STATEMENT_1 ,EMPLOYEE_ID ,EXPENSE_ACCOUNT_ID ,FAIR_SIZE ,FAIR_TYPE_ID ,FAX ,FINANCIAL ,FORWARDERS_ADDRESS_ID ,FORWARDER_ADDRESS ,FREIGHT_ESTIMATE_METHOD_ID ,FREIGHT_RATE ,FULL_NAME ,HOME_PHONE ,INCOTERM ,IS1099ELIGIBLE ,ISEMAILHTML ,ISEMAILPDF ,ISINACTIVE ,IS_PERSON ,LABOR_COST ,LAST_MODIFIED_DATE ,LAST_SALES_ACTIVITY ,LEGACY_CUSTOMER_IDCUSTOM ,LINE1 ,LINE2 ,LINE3 ,LINE_OF_BUSINESS_ID ,LINE_OF_BUSINESS ,LOGINACCESS ,LSA_LINK ,LSA_LINK_NAME ,MOBILE_PHONE ,MOE_ID ,NAME ,NO_OF_CHILDREN_ENROLLED ,OLD_CUSTOMER_CODE ,OLD_PARENT_CODE ,OPENBALANCE ,OPENBALANCE_FOREIGN ,OPENING_BALANCE ,PAYABLES_ACCOUNT_ID ,PAYMENT_TERMS_ID ,PHILHEALTH ,PHONE ,PRICE_GROUP_ID ,PRINTONCHECKAS ,PROJECT_SCOPE_STATEMENT ,PROVIDENT_FUND_NUMBER ,PURCHASEORDERAMOUNT ,PURCHASEORDERQUANTITY ,PURCHASEORDERQUANTITYDIFF ,RECEIPTAMOUNT ,RECEIPTQUANTITY ,RECEIPTQUANTITYDIFF ,REGION_ID ,REWARDS_BAND_ID ,REWARD_EARNER_ID ,ROUTE_CODE_ID ,SALES_TERRITORYDO_NOT_USE_ID ,SCHEMAI1L_FOR_INVOICE ,SCHEMAIL_FOR_INVOICE ,SCHOLASTIC_SALES_TERRITORY_ID ,SELLING_RIGHTS_ID ,SHIPADDRESS ,SHIPPING_PREFERENCE_ID ,SNIPP_MEMBER_ID ,SOR_DISCOUNT_ID ,SOR_DURATION_FROM_DAYS ,SOR_DURATION_TO_DAYS ,SOR_TAG ,SOR_THRESHOLD ,SPONSOR ,STAPLES ,STATE ,SUBSIDIARY ,SUBSIDIARY_NAME ,TAXIDNUM ,TAX_CONTACT_FIRST_NAME ,TAX_CONTACT_ID ,TAX_CONTACT_LAST_NAME ,TAX_CONTACT_MIDDLE_NAME ,THIRD_PARTY ,TIN ,TOTAL_QUANTITY ,TRANSACTIONS_NEED_APPROVAL ,UEN ,UK_OTC_CODE ,UNBILLED_ORDERS ,UNBILLED_ORDERS_FOREIGN ,URL ,US_OTC_CODE ,VAT_REGISTRATION_NO ,VENDOR_EXTID ,VENDOR_ID ,VENDOR_TYPE_ID ,VENDOR_TYPE ,ZIPCODE ,ZONE_NUMBER_ID from dw_prestage.vendors_insert;

/* stage -> insert into stage records which have been created */
insert into dw_stage.vendors (ABCD_MARKER_ID ,ACCOUNTNUMBER ,ACTUAL_COST ,ALTEMAIL ,ALTERNATE_CUSTOMER_EMAIL ,ALTERNATE_CUSTOMER_EMAIL1 ,ALTERNATE_CUSTOMER_EMAIL2 ,ALTPHONE ,APPLY_FREIGHT ,BACKORDERS_ALLOWED ,BACK_ORDER_SPLIT ,BILLADDRESS ,BILLING_CLASS_ID ,BOOK_FAIRS_CONSULTANT_ID ,BOOK_FAIR_ABCD_MARKER ,BOOK_FAIR_SIZE_ID ,BRN ,BUSINESS_STYLE_ID ,CARRIER_ADDRESS ,CARRIER_LABEL_ID ,CITY ,COMMENTS ,COMPANYNAME ,COST_EXPIRED ,COUNTRY ,CREATE_DATE ,CREDITLIMIT ,CTC ,CURRENCY_ID ,CURRENCY_NAME ,CUSTOMER_ID ,DATE_CUSTOMER_STATEMENT_SENT ,DATE_LAST_MODIFIED ,DECILE_ID ,DEFAULT_DISCOUNT_ID ,DEFAULT_DISCOUNT_RATE ,DEFAULT_WT_CODE_ID ,DELIVERY_INSTRUCTION ,DIRECT_DEBIT ,EFT_BILL_PAYMENT ,EFT_CUSTOMER_REFUND_PAYMENT ,EFT_FILE_FORMAT_ID ,ELIGIBLE_FOR_APPROVAL ,EMAIL ,EMAIL_ADDRESS ,EMAIL_ADDRESS_FOR_PAYMENT_NOT ,EMAIL_ADDRESS_FOR_PAYMENT_NO_0 ,EMAIL_FOR_CUSTOMER_STATEMENT ,EMAIL_FOR_CUSTOMER_STATEMENT_ ,EMAIL_FOR_CUSTOMER_STATEMENT_0 ,EMAIL_FOR_CUSTOMER_STATEMENT_1 ,EMPLOYEE_ID ,EXPENSE_ACCOUNT_ID ,FAIR_SIZE ,FAIR_TYPE_ID ,FAX ,FINANCIAL ,FORWARDERS_ADDRESS_ID ,FORWARDER_ADDRESS ,FREIGHT_ESTIMATE_METHOD_ID ,FREIGHT_RATE ,FULL_NAME ,HOME_PHONE ,INCOTERM ,IS1099ELIGIBLE ,ISEMAILHTML ,ISEMAILPDF ,ISINACTIVE ,IS_PERSON ,LABOR_COST ,LAST_MODIFIED_DATE ,LAST_SALES_ACTIVITY ,LEGACY_CUSTOMER_IDCUSTOM ,LINE1 ,LINE2 ,LINE3 ,LINE_OF_BUSINESS_ID ,LINE_OF_BUSINESS ,LOGINACCESS ,LSA_LINK ,LSA_LINK_NAME ,MOBILE_PHONE ,MOE_ID ,NAME ,NO_OF_CHILDREN_ENROLLED ,OLD_CUSTOMER_CODE ,OLD_PARENT_CODE ,OPENBALANCE ,OPENBALANCE_FOREIGN ,OPENING_BALANCE ,PAYABLES_ACCOUNT_ID ,PAYMENT_TERMS_ID ,PHILHEALTH ,PHONE ,PRICE_GROUP_ID ,PRINTONCHECKAS ,PROJECT_SCOPE_STATEMENT ,PROVIDENT_FUND_NUMBER ,PURCHASEORDERAMOUNT ,PURCHASEORDERQUANTITY ,PURCHASEORDERQUANTITYDIFF ,RECEIPTAMOUNT ,RECEIPTQUANTITY ,RECEIPTQUANTITYDIFF ,REGION_ID ,REWARDS_BAND_ID ,REWARD_EARNER_ID ,ROUTE_CODE_ID ,SALES_TERRITORYDO_NOT_USE_ID ,SCHEMAI1L_FOR_INVOICE ,SCHEMAIL_FOR_INVOICE ,SCHOLASTIC_SALES_TERRITORY_ID ,SELLING_RIGHTS_ID ,SHIPADDRESS ,SHIPPING_PREFERENCE_ID ,SNIPP_MEMBER_ID ,SOR_DISCOUNT_ID ,SOR_DURATION_FROM_DAYS ,SOR_DURATION_TO_DAYS ,SOR_TAG ,SOR_THRESHOLD ,SPONSOR ,STAPLES ,STATE ,SUBSIDIARY ,SUBSIDIARY_NAME ,TAXIDNUM ,TAX_CONTACT_FIRST_NAME ,TAX_CONTACT_ID ,TAX_CONTACT_LAST_NAME ,TAX_CONTACT_MIDDLE_NAME ,THIRD_PARTY ,TIN ,TOTAL_QUANTITY ,TRANSACTIONS_NEED_APPROVAL ,UEN ,UK_OTC_CODE ,UNBILLED_ORDERS ,UNBILLED_ORDERS_FOREIGN ,URL ,US_OTC_CODE ,VAT_REGISTRATION_NO ,VENDOR_EXTID ,VENDOR_ID ,VENDOR_TYPE_ID ,VENDOR_TYPE ,ZIPCODE ,ZONE_NUMBER_ID)
select ABCD_MARKER_ID ,ACCOUNTNUMBER ,ACTUAL_COST ,ALTEMAIL ,ALTERNATE_CUSTOMER_EMAIL ,ALTERNATE_CUSTOMER_EMAIL1 ,ALTERNATE_CUSTOMER_EMAIL2 ,ALTPHONE ,APPLY_FREIGHT ,BACKORDERS_ALLOWED ,BACK_ORDER_SPLIT ,BILLADDRESS ,BILLING_CLASS_ID ,BOOK_FAIRS_CONSULTANT_ID ,BOOK_FAIR_ABCD_MARKER ,BOOK_FAIR_SIZE_ID ,BRN ,BUSINESS_STYLE_ID ,CARRIER_ADDRESS ,CARRIER_LABEL_ID ,CITY ,COMMENTS ,COMPANYNAME ,COST_EXPIRED ,COUNTRY ,CREATE_DATE ,CREDITLIMIT ,CTC ,CURRENCY_ID ,CURRENCY_NAME ,CUSTOMER_ID ,DATE_CUSTOMER_STATEMENT_SENT ,DATE_LAST_MODIFIED ,DECILE_ID ,DEFAULT_DISCOUNT_ID ,DEFAULT_DISCOUNT_RATE ,DEFAULT_WT_CODE_ID ,DELIVERY_INSTRUCTION ,DIRECT_DEBIT ,EFT_BILL_PAYMENT ,EFT_CUSTOMER_REFUND_PAYMENT ,EFT_FILE_FORMAT_ID ,ELIGIBLE_FOR_APPROVAL ,EMAIL ,EMAIL_ADDRESS ,EMAIL_ADDRESS_FOR_PAYMENT_NOT ,EMAIL_ADDRESS_FOR_PAYMENT_NO_0 ,EMAIL_FOR_CUSTOMER_STATEMENT ,EMAIL_FOR_CUSTOMER_STATEMENT_ ,EMAIL_FOR_CUSTOMER_STATEMENT_0 ,EMAIL_FOR_CUSTOMER_STATEMENT_1 ,EMPLOYEE_ID ,EXPENSE_ACCOUNT_ID ,FAIR_SIZE ,FAIR_TYPE_ID ,FAX ,FINANCIAL ,FORWARDERS_ADDRESS_ID ,FORWARDER_ADDRESS ,FREIGHT_ESTIMATE_METHOD_ID ,FREIGHT_RATE ,FULL_NAME ,HOME_PHONE ,INCOTERM ,IS1099ELIGIBLE ,ISEMAILHTML ,ISEMAILPDF ,ISINACTIVE ,IS_PERSON ,LABOR_COST ,LAST_MODIFIED_DATE ,LAST_SALES_ACTIVITY ,LEGACY_CUSTOMER_IDCUSTOM ,LINE1 ,LINE2 ,LINE3 ,LINE_OF_BUSINESS_ID ,LINE_OF_BUSINESS ,LOGINACCESS ,LSA_LINK ,LSA_LINK_NAME ,MOBILE_PHONE ,MOE_ID ,NAME ,NO_OF_CHILDREN_ENROLLED ,OLD_CUSTOMER_CODE ,OLD_PARENT_CODE ,OPENBALANCE ,OPENBALANCE_FOREIGN ,OPENING_BALANCE ,PAYABLES_ACCOUNT_ID ,PAYMENT_TERMS_ID ,PHILHEALTH ,PHONE ,PRICE_GROUP_ID ,PRINTONCHECKAS ,PROJECT_SCOPE_STATEMENT ,PROVIDENT_FUND_NUMBER ,PURCHASEORDERAMOUNT ,PURCHASEORDERQUANTITY ,PURCHASEORDERQUANTITYDIFF ,RECEIPTAMOUNT ,RECEIPTQUANTITY ,RECEIPTQUANTITYDIFF ,REGION_ID ,REWARDS_BAND_ID ,REWARD_EARNER_ID ,ROUTE_CODE_ID ,SALES_TERRITORYDO_NOT_USE_ID ,SCHEMAI1L_FOR_INVOICE ,SCHEMAIL_FOR_INVOICE ,SCHOLASTIC_SALES_TERRITORY_ID ,SELLING_RIGHTS_ID ,SHIPADDRESS ,SHIPPING_PREFERENCE_ID ,SNIPP_MEMBER_ID ,SOR_DISCOUNT_ID ,SOR_DURATION_FROM_DAYS ,SOR_DURATION_TO_DAYS ,SOR_TAG ,SOR_THRESHOLD ,SPONSOR ,STAPLES ,STATE ,SUBSIDIARY ,SUBSIDIARY_NAME ,TAXIDNUM ,TAX_CONTACT_FIRST_NAME ,TAX_CONTACT_ID ,TAX_CONTACT_LAST_NAME ,TAX_CONTACT_MIDDLE_NAME ,THIRD_PARTY ,TIN ,TOTAL_QUANTITY ,TRANSACTIONS_NEED_APPROVAL ,UEN ,UK_OTC_CODE ,UNBILLED_ORDERS ,UNBILLED_ORDERS_FOREIGN ,URL ,US_OTC_CODE ,VAT_REGISTRATION_NO ,VENDOR_EXTID ,VENDOR_ID ,VENDOR_TYPE_ID ,VENDOR_TYPE ,ZIPCODE ,ZONE_NUMBER_ID from dw_prestage.vendors
where exists ( select 1 from 
dw_prestage.vendors_update
where dw_prestage.vendors_update.vendor_id = dw_prestage.vendors.vendor_id);

commit;

/* dimension ->insert new records in dim vendors */

insert into dw.vendors ( 
  VENDOR_ID        
 ,VENDOR_EXTID     
 ,NAME             
 ,EMAIL            
 ,FULL_NAME        
 ,BILLADDRESS      
 ,SHIPADDRESS      
 ,ACCOUNTNUMBER    
 ,LINE1            
 ,LINE2            
 ,LINE3            
 ,ZIPCODE          
 ,CITY             
 ,STATE            
 ,COUNTRY          
 ,COMPANYNAME      
 ,CURRENCY         
 ,CURRENCY_ID      
 ,EFT_BILL_PAYMENT 
 ,IS1099ELIGIBLE   
 ,ISINACTIVE       
 ,TYPE             
 ,LINE_OF_BUSINESS 
 ,LINE_OF_BUSINESS_ID
 ,SUBSIDIARY_NAME  
 ,SUBSIDIARY_ID    
 ,VENDOR_TYPE      
 ,DATE_ACTIVE_FROM 
 ,DATE_ACTIVE_TO   
 ,DW_ACTIVE  )
select 
 VENDOR_ID
 ,DECODE(LENGTH(VENDOR_EXTID),0,'NA_GDW',VENDOR_EXTID)
 ,DECODE(LENGTH(NAME),0,'NA_GDW',NAME )         
 ,DECODE(LENGTH(EMAIL),0,'NA_GDW',EMAIL   )      
 ,DECODE(LENGTH(FULL_NAME),0,'NA_GDW', FULL_NAME   )    
 ,DECODE(LENGTH(BILLADDRESS),0,'NA_GDW', BILLADDRESS )    
 ,DECODE(LENGTH(SHIPADDRESS),0,'NA_GDW', SHIPADDRESS )    
 ,DECODE(LENGTH(ACCOUNTNUMBER),0,'NA_GDW', ACCOUNTNUMBER   )
 ,DECODE(LENGTH(LINE1),0,'NA_GDW', LINE1  )         
 ,DECODE(LENGTH(LINE2),0,'NA_GDW', LINE2  )
 ,DECODE(LENGTH(LINE3),0,'NA_GDW', LINE3  )         
 ,DECODE(LENGTH(ZIPCODE),0,'NA_GDW', ZIPCODE)          
 ,DECODE(LENGTH(CITY),0,'NA_GDW',CITY )             
 ,DECODE(LENGTH(STATE),0,'NA_GDW',STATE )            
 ,DECODE(LENGTH(COUNTRY),0,'NA_GDW', COUNTRY )         
 ,DECODE(LENGTH(COMPANYNAME),0,'NA_GDW',COMPANYNAME)       
 ,DECODE(LENGTH(CURRENCY_NAME),0,'NA_GDW', CURRENCY_NAME)
 ,NVL(CURRENCY_ID , -99)     
 ,NVL(EFT_BILL_PAYMENT,'NA_GDW')
 ,NVL(IS1099ELIGIBLE ,'NA_GDW')  
 ,NVL(ISINACTIVE,'NA_GDW')       
 ,NVL(IS_PERSON ,'NA_GDW')            
 ,DECODE(LENGTH(LINE_OF_BUSINESS),0,'NA_GDW', LINE_OF_BUSINESS) 
 ,NVL(LINE_OF_BUSINESS_ID , -99)
 ,DECODE(LENGTH(SUBSIDIARY_NAME),0,'NA_GDW', SUBSIDIARY_NAME) 
 ,NVL(SUBSIDIARY , -99) 
 ,DECODE(LENGTH(VENDOR_TYPE ),0,'NA_GDW', VENDOR_TYPE) 
 ,sysdate
 ,'9999-12-31 23:59:59'
 ,'A'
  from 
dw_prestage.vendors_insert A;

/* dimension -> update old record as part of SCD2 maintenance*/

UPDATE dw.vendors
   SET dw_active = 'I' ,
	   DATE_ACTIVE_TO = (sysdate -1)
WHERE dw_active = 'A'
      and sysdate >= date_active_from and sysdate < date_active_to
	  and exists ( select 1 from dw_prestage.vendors_update
	  WHERE dw.vendors.vendor_id = dw_prestage.vendors_update.vendor_id
	  and dw_prestage.vendors_update.ch_type = 2);

/* dimension -> insert the new records as part of SCD2 maintenance*/

insert into dw.vendors ( 
  VENDOR_ID        
 ,VENDOR_EXTID     
 ,NAME             
 ,EMAIL            
 ,FULL_NAME        
 ,BILLADDRESS      
 ,SHIPADDRESS      
 ,ACCOUNTNUMBER    
 ,LINE1            
 ,LINE2            
 ,LINE3            
 ,ZIPCODE          
 ,CITY             
 ,STATE            
 ,COUNTRY          
 ,COMPANYNAME      
 ,CURRENCY         
 ,CURRENCY_ID      
 ,EFT_BILL_PAYMENT 
 ,IS1099ELIGIBLE   
 ,ISINACTIVE       
 ,TYPE             
 ,LINE_OF_BUSINESS 
 ,LINE_OF_BUSINESS_ID
 ,SUBSIDIARY_NAME  
 ,SUBSIDIARY_ID    
 ,VENDOR_TYPE      
 ,DATE_ACTIVE_FROM 
 ,DATE_ACTIVE_TO   
 ,DW_ACTIVE  )
select 
VENDOR_ID
 ,DECODE(LENGTH(VENDOR_EXTID),0,'NA_GDW',VENDOR_EXTID)
 ,DECODE(LENGTH(NAME),0,'NA_GDW',NAME )         
 ,DECODE(LENGTH(EMAIL),0,'NA_GDW',EMAIL   )      
 ,DECODE(LENGTH(FULL_NAME),0,'NA_GDW', FULL_NAME   )    
 ,DECODE(LENGTH(BILLADDRESS),0,'NA_GDW', BILLADDRESS )    
 ,DECODE(LENGTH(SHIPADDRESS),0,'NA_GDW', SHIPADDRESS )    
 ,DECODE(LENGTH(ACCOUNTNUMBER),0,'NA_GDW', ACCOUNTNUMBER   )
 ,DECODE(LENGTH(LINE1),0,'NA_GDW', LINE1  )         
 ,DECODE(LENGTH(LINE2),0,'NA_GDW', LINE2  )
 ,DECODE(LENGTH(LINE3),0,'NA_GDW', LINE3  )         
 ,DECODE(LENGTH(ZIPCODE),0,'NA_GDW', ZIPCODE)          
 ,DECODE(LENGTH(CITY),0,'NA_GDW',CITY )             
 ,DECODE(LENGTH(STATE),0,'NA_GDW',STATE )            
 ,DECODE(LENGTH(COUNTRY),0,'NA_GDW', COUNTRY )         
 ,DECODE(LENGTH(COMPANYNAME),0,'NA_GDW',COMPANYNAME)       
 ,DECODE(LENGTH(CURRENCY_NAME),0,'NA_GDW', CURRENCY_NAME)
 ,NVL(CURRENCY_ID , -99)     
 ,NVL(EFT_BILL_PAYMENT,'NA_GDW')
 ,NVL(IS1099ELIGIBLE ,'NA_GDW')  
 ,NVL(ISINACTIVE,'NA_GDW')       
 ,NVL(IS_PERSON ,'NA_GDW')            
 ,DECODE(LENGTH(LINE_OF_BUSINESS),0,'NA_GDW', LINE_OF_BUSINESS) 
 ,NVL(LINE_OF_BUSINESS_ID , -99)
 ,DECODE(LENGTH(SUBSIDIARY_NAME),0,'NA_GDW', SUBSIDIARY_NAME) 
 ,NVL(SUBSIDIARY , -99) 
 ,DECODE(LENGTH(VENDOR_TYPE ),0,'NA_GDW', VENDOR_TYPE) 
 ,sysdate
 ,'9999-12-31 23:59:59'
 ,'A'
from 
dw_prestage.vendors A
WHERE exists (select 1 from dw_prestage.vendors_update
	  WHERE a.vendor_id = dw_prestage.vendors_update.vendor_id
	  and dw_prestage.vendors_update.ch_type = 2) ;
	  
/* dimension -> update records as part of SCD1 maintenance */

UPDATE dw.vendors 
   SET  VENDOR_EXTID          =  DECODE(LENGTH(dw_prestage.vendors.VENDOR_EXTID),0,'NA_GDW',dw_prestage.vendors.VENDOR_EXTID)
      , NAME                  =  DECODE(LENGTH(dw_prestage.vendors.NAME),0,'NA_GDW',dw_prestage.vendors.NAME)
	  , EMAIL                 =  DECODE(LENGTH(dw_prestage.vendors.EMAIL),0,'NA_GDW',dw_prestage.vendors.EMAIL)
	  , FULL_NAME             =  DECODE(LENGTH(dw_prestage.vendors.FULL_NAME),0,'NA_GDW',dw_prestage.vendors.FULL_NAME)
	  , EFT_BILL_PAYMENT      =  DECODE(LENGTH(dw_prestage.vendors.EFT_BILL_PAYMENT),0,'NA_GDW',dw_prestage.vendors.EFT_BILL_PAYMENT)
	  ,IS1099ELIGIBLE        =  DECODE(LENGTH(dw_prestage.vendors.IS1099ELIGIBLE),0,'NA_GDW',dw_prestage.vendors.IS1099ELIGIBLE)
	  ,ISINACTIVE            =  DECODE(LENGTH(dw_prestage.vendors.ISINACTIVE),0,'NA_GDW',dw_prestage.vendors.ISINACTIVE)
	  ,TYPE                  =  DECODE(LENGTH(dw_prestage.vendors.IS_PERSON),0,'NA_GDW',dw_prestage.vendors.IS_PERSON)
	  ,LINE_OF_BUSINESS      =  DECODE(LENGTH(dw_prestage.vendors.LINE_OF_BUSINESS),0,'NA_GDW',dw_prestage.vendors.LINE_OF_BUSINESS)
	  ,LINE_OF_BUSINESS_ID   =  NVL(dw_prestage.vendors.LINE_OF_BUSINESS_ID,-99)
	  ,SUBSIDIARY_NAME       =  DECODE(LENGTH(dw_prestage.vendors.SUBSIDIARY_NAME),0,'NA_GDW',dw_prestage.vendors.SUBSIDIARY_NAME)
	  ,SUBSIDIARY_ID         =  NVL(dw_prestage.vendors.SUBSIDIARY,-99)
	  ,VENDOR_TYPE           =  DECODE(LENGTH(dw_prestage.vendors.VENDOR_TYPE),0,'NA_GDW',dw_prestage.vendors.VENDOR_TYPE)
   FROM dw_prestage.vendors
WHERE dw.vendors.vendor_id = dw_prestage.vendors.vendor_id
and exists (select 1 from dw_prestage.vendors_update
	  WHERE dw_prestage.vendors.vendor_id = dw_prestage.vendors_update.vendor_id
	  and dw_prestage.vendors_update.ch_type = 1);

/* dimension -> logically delete dw records */

update dw.vendors
set DATE_ACTIVE_TO = sysdate-1,
dw_active = 'I'
FROM dw_prestage.vendors_delete
WHERE dw.vendors.vendor_id = dw_prestage.vendors_delete.vendor_id;

commit;
