SELECT 
A.LIST_ID STATUS_ID, A.LIST_ITEM_NAME STATUS,
B.LIST_ID ROUTE_ID, B.LIST_ITEM_NAME ROUTE,
C.LIST_ID MARKER_ID, C.LIST_ITEM_NAME MARKER,
D.LIST_ID FAIR_TYPE_ID, D.LIST_ITEM_NAME FAIR_TYPE,
E.LIST_ID INVOICE_OPTION_ID, E.LIST_ITEM_NAME INVOICE_OPTION
FROM  
(select list_id list_id , TO_CHAR(LIST_ITEM_NAME) LIST_ITEM_NAME FROM BOOK_FAIRS_STATUS WHERE IS_RECORD_INACTIVE = 'F'
 UNION ALL
 SELECT -99 list_id, 'NA_GDW' LIST_ITEM_NAME FROM BOOK_FAIRS_STATUS WHERE ROWNUM=1
 UNION ALL
 SELECT 0 list_id, 'NA_ERR' LIST_ITEM_NAME FROM BOOK_FAIRS_STATUS WHERE ROWNUM=1) A,
 (select list_id list_id , TO_CHAR(LIST_ITEM_NAME) LIST_ITEM_NAME FROM BOOK_FAIRS_TRUCK_ROUTES WHERE IS_RECORD_INACTIVE = 'F'
 UNION ALL
 SELECT -99 list_id, 'NA_GDW' LIST_ITEM_NAME FROM BOOK_FAIRS_TRUCK_ROUTES WHERE ROWNUM=1
 UNION ALL
 SELECT 0 list_id, 'NA_ERR' LIST_ITEM_NAME FROM BOOK_FAIRS_TRUCK_ROUTES WHERE ROWNUM=1) B,
 (select list_id list_id , TO_CHAR(LIST_ITEM_NAME) LIST_ITEM_NAME FROM BOOK_FAIR_ABCDO_MARKER_LIST WHERE IS_RECORD_INACTIVE = 'F'
 UNION ALL
 SELECT -99 list_id, 'NA_GDW' LIST_ITEM_NAME FROM BOOK_FAIR_ABCDO_MARKER_LIST WHERE ROWNUM=1
 UNION ALL
 SELECT 0 list_id, 'NA_ERR' LIST_ITEM_NAME FROM BOOK_FAIR_ABCDO_MARKER_LIST WHERE ROWNUM=1) C,
 (select list_id list_id , TO_CHAR(LIST_ITEM_NAME) LIST_ITEM_NAME FROM FAIR_TYPE_LIST WHERE IS_RECORD_INACTIVE = 'F'
 UNION ALL
 SELECT -99 list_id, 'NA_GDW' LIST_ITEM_NAME FROM FAIR_TYPE_LIST WHERE ROWNUM=1
 UNION ALL
 SELECT 0 list_id, 'NA_ERR' LIST_ITEM_NAME FROM FAIR_TYPE_LIST WHERE ROWNUM=1) D,
 (select list_id list_id , TO_CHAR(LIST_ITEM_NAME) LIST_ITEM_NAME FROM BOOK_FAIRS_INVOICE_OPTIONS WHERE IS_RECORD_INACTIVE = 'F'
 UNION ALL
 SELECT -99 list_id, 'NA_GDW' LIST_ITEM_NAME FROM BOOK_FAIRS_INVOICE_OPTIONS WHERE ROWNUM=1
 UNION ALL
 SELECT 0 list_id, 'NA_ERR' LIST_ITEM_NAME FROM BOOK_FAIRS_INVOICE_OPTIONS WHERE ROWNUM=1) E
 ORDER BY
 STATUS_ID, ROUTE_ID , MARKER_ID ,FAIR_TYPE_ID,INVOICE_OPTION_ID ;
