
CREATE SCHEMA if not exists dw;

DROP TABLE if exists dw.book_fairs;

CREATE TABLE dw.book_fairs 
(
  BOOK_FAIR_KEY       BIGINT IDENTITY(0,1), 
  FAIR_STATUS_ID      INTEGER,
  FAIR_STATUS         VARCHAR(1000),
  ROUTE_ID            INTEGER,
  ROUTE               VARCHAR(1000),
  MARKER_ID           INTEGER,
  MARKER              VARCHAR(1000),
  FAIR_TYPE_ID        INTEGER,
  FAIR_TYPE           VARCHAR(1000),
  INVOICE_OPTION_ID   INTEGER,
  INVOICE_OPTION      VARCHAR(1000),
  DATE_ACTIVE_FROM           TIMESTAMP,
  DATE_ACTIVE_TO             TIMESTAMP,
  DW_ACTIVE                  VARCHAR(1),
  PRIMARY KEY (BOOK_FAIR_KEY)
)
DISTSTYLE ALL INTERLEAVED SORTKEY (BOOK_FAIR_KEY,FAIR_STATUS_ID,ROUTE_ID,MARKER_ID,FAIR_TYPE_ID,INVOICE_OPTION_ID,DW_ACTIVE);

