CREATE SCHEMA if not exists dw;

DROP TABLE if exists dw.cost_center;

CREATE TABLE dw.cost_center 
(
  department_key               BIGINT IDENTITY(0,1),
  DEPARTMENT_ID                INTEGER,
  NAME                         VARCHAR(50),
  FULL_NAME                    VARCHAR(2000),
  DEPARTMENT_EXTID             VARCHAR(300),
  ACCPAC_COST_CENTER_CODES     VARCHAR(4000),
  COST_CENTER_CODE             VARCHAR(4000),
  HYPERION_COST_CENTER_CODES   VARCHAR(4000),
  PARENT_COST_CENTER           VARCHAR(50),
  PARENT_COST_CENTER_ID        INTEGER,
  ISINACTIVE                   VARCHAR(10),
  DATE_ACTIVE_FROM             TIMESTAMP,
  DATE_ACTIVE_TO               TIMESTAMP,
  DW_ACTIVE                    VARCHAR(1),
  PRIMARY KEY (department_key,department_ID)
)
DISTSTYLE ALL INTERLEAVED SORTKEY (department_key,department_ID,COST_CENTER_CODE,NAME,DW_ACTIVE);


INSERT INTO dw.cost_center
(
  DEPARTMENT_ID,
  NAME,
  FULL_NAME,
  DEPARTMENT_EXTID,
  ACCPAC_COST_CENTER_CODES,
  COST_CENTER_CODE,
  HYPERION_COST_CENTER_CODES,
  PARENT_COST_CENTER,
  PARENT_COST_CENTER_ID,
  ISINACTIVE,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE
)
SELECT -99 AS DEPARTMENT_ID,
       'NA_GDW' AS NAME,
       'NA_GDW' AS FULL_NAME,
       'NA_GDW' AS DEPARTMENT_EXTID,
       'NA_GDW' AS ACCPAC_COST_CENTER_CODES,
       'NA_GDW' AS COST_CENTER_CODE,
       'NA_GDW' AS HYPERION_COST_CENTER_CODES,
       'NA_GDW' AS PARENT_COST_CENTER,
       -99 AS PARENT_COST_CENTER_ID,
       'NA_GDW' AS ISINACTIVE,
       SYSDATE AS DATE_ACTIVE_FROM,
       '9999-12-31 23:59:59' AS DATE_ACTIVE_TO,
       'A' AS DW_ACTIVE;

INSERT INTO dw.cost_center
(
  DEPARTMENT_ID,
  NAME,
  FULL_NAME,
  DEPARTMENT_EXTID,
  ACCPAC_COST_CENTER_CODES,
  COST_CENTER_CODE,
  HYPERION_COST_CENTER_CODES,
  PARENT_COST_CENTER,
  PARENT_COST_CENTER_ID,
  ISINACTIVE,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE
)
SELECT 0 AS DEPARTMENT_ID,
       'NA_ERR' AS NAME,
       'NA_ERR' AS FULL_NAME,
       'NA_ERR' AS DEPARTMENT_EXTID,
       'NA_ERR' AS ACCPAC_COST_CENTER_CODES,
       'NA_ERR' AS COST_CENTER_CODE,
       'NA_ERR' AS HYPERION_COST_CENTER_CODES,
       'NA_ERR' AS PARENT_COST_CENTER,
       0 AS PARENT_COST_CENTER_ID,
       'NA_ERR' AS ISINACTIVE,
       SYSDATE AS DATE_ACTIVE_FROM,
       '9999-12-31 23:59:59' AS DATE_ACTIVE_TO,
       'A' AS DW_ACTIVE;

COMMIT;

