SELECT
REPLACE(REPLACE(DEPARTMENTS.ACCPAC_COST_CENTER_CODES,CHR(10),' '),CHR(13),' ') AS ACCPAC_COST_CENTER_CODES , 
REPLACE(REPLACE(DEPARTMENTS.COST_CENTER_CODE,CHR(10),' '),CHR(13),' ') AS COST_CENTER_CODE , 
TO_CHAR(DEPARTMENTS.DATE_LAST_MODIFIED,'YYYY-MM-DD HH24:MI:SS') AS DATE_LAST_MODIFIED , 
REPLACE(REPLACE(DEPARTMENTS.DEPARTMENT_EXTID,CHR(10),' '),CHR(13),' ') AS DEPARTMENT_EXTID , 
TO_CHAR(DEPARTMENTS.DEPARTMENT_ID) AS DEPARTMENT_ID , 
REPLACE(REPLACE(DEPARTMENTS.FULL_NAME,CHR(10),' '),CHR(13),' ') AS FULL_NAME , 
REPLACE(REPLACE(DEPARTMENTS.HYPERION_COST_CENTER_CODES,CHR(10),' '),CHR(13),' ') AS HYPERION_COST_CENTER_CODES , 
ISINACTIVE , 
NAME , 
TO_CHAR(DEPARTMENTS.PARENT_ID) AS PARENT_ID 
FROM
DEPARTMENTS;
