select 
TO_CHAR(TRANSACTIONS.transaction_id) AS transaction_id,
TO_CHAR(TRANSACTION_LINES.transaction_line_id) AS transaction_line_id,
REPLACE(REPLACE(TRANSACTIONS.transaction_number,CHR (10),' '),CHR (13),' ') as VRA_NUMBER,
TO_CHAR(TRANSACTIONS.ENTITY_ID) AS VENDOR_ID,
TO_CHAR(TRANSACTIONS.CREATED_FROM_ID) AS CREATED_FROM_ID,  /* po ID*/ /* GET PO NUMBER */
TO_CHAR(TRANSACTIONS.CREATED_BY_ID) AS CREATED_BY_ID,
TO_CHAR(TRANSACTION_LINES.SHIPMENT_RECEIVED,'YYYY-MM-DD HH24:MI:SS') AS SHIPMENT_RECEIVED,
TO_CHAR(TRANSACTIONS.CREATE_DATE,'YYYY-MM-DD HH24:MI:SS') AS CREATE_DATE,
TO_CHAR(TRANSACTION_LINES.SUBSIDIARY_ID) AS SUBSIDIARY_ID,
TO_CHAR(TRANSACTION_LINES.DEPARTMENT_ID) AS DEPARTMENT_ID,
TO_CHAR(TRANSACTION_LINES.ITEM_ID) AS ITEM_ID,
TO_CHAR(TRANSACTIONS.LOCATION_ID) AS LOCATION_ID,
TRANSACTIONS.EXCHANGE_RATE,
REPLACE(REPLACE(TRANSACTION_ADDRESS.BILL_ADDRESS_LINE_1,CHR (10),' '),CHR (13),' ') AS VENDOR_ADDRESS_LINE_1,
REPLACE(REPLACE(TRANSACTION_ADDRESS.BILL_ADDRESS_LINE_2,CHR (10),' '),CHR (13),' ') AS VENDOR_ADDRESS_LINE_2,
REPLACE(REPLACE(TRANSACTION_ADDRESS.BILL_ADDRESS_LINE_3,CHR (10),' '),CHR (13),' ') AS VENDOR_ADDRESS_LINE_3,
REPLACE(REPLACE(TRANSACTION_ADDRESS.BILL_CITY,CHR (10),' '),CHR (13),' ') AS VENDOR_CITY,
REPLACE(REPLACE(TRANSACTION_ADDRESS.BILL_COUNTRY,CHR (10),' '),CHR (13),' ') AS VENDOR_COUNTRY,
REPLACE(REPLACE(TRANSACTION_ADDRESS.BILL_STATE,CHR (10),' '),CHR (13),' ') AS VENDOR_STATE,
REPLACE(REPLACE(TRANSACTION_ADDRESS.BILL_ZIP,CHR (10),' '),CHR (13),' ') AS VENDOR_ZIP,
TRANSACTION_LINES.ITEM_COUNT AS ITEM_COUNT,
TRANSACTION_LINES.ITEM_GROSS_AMOUNT AS ITEM_GROSS_AMOUNT,
TRANSACTION_LINES.AMOUNT AS AMOUNT,
TRANSACTION_LINES.AMOUNT_FOREIGN AS AMOUNT_FOREIGN,
TRANSACTION_LINES.NET_AMOUNT AS NET_AMOUNT,
TRANSACTION_LINES.NET_AMOUNT_FOREIGN AS NET_AMOUNT_FOREIGN,
TRANSACTION_LINES.GROSS_AMOUNT AS GROSS_AMOUNT,
TRANSACTION_LINES.ITEM_UNIT_PRICE AS ITEM_UNIT_PRICE,
TRANSACTION_LINES.NUMBER_BILLED AS QUANTITY_BILLED,
TRANSACTION_LINES.QUANTITY_RECEIVED_IN_SHIPMENT AS QUANTITY_SHIPPED,
/*TRANSACTION_LINES.account_id,*/
TO_CHAR(TRANSACTION_LINES.date_closed,'YYYY-MM-DD HH24:MI:SS') AS CLOSE_DATE,
/*TRANSACTION_LINES.company_id,*/
TO_CHAR(C.TAX_ITEM_ID) AS TAX_ITEM_ID,
TRANSACTION_LINES.transaction_order,
c.amount tax_amount,
c.amount_foreign tax_amount_foreign,
Decode(d.name,
             'Vendor Return Authorizations','VRA_HDR',
             decode(c.transaction_line_id,NULL,'VRA_TAX','VRA_LINE')
       )  AS line_type,
     a.currency_id,
     b.class_id
FROM transaction_lines b 
     INNER JOIN transactions a ON ( a.transaction_id = b.transaction_id )
     LEFT OUTER JOIN accounts d ON (TRANSACTION_LINES.account_id = accounts.account_id)
     LEFT OUTER JOIN transaction_address e ON (TRANSACTION_LINES.transaction_id = transaction_address.transaction_id )
      LEFT OUTER JOIN transaction_tax_detail c
               ON (TRANSACTION_LINES.transaction_id = transaction_tax_detail.transaction_id
              AND TRANSACTION_LINES.transaction_line_id = transaction_tax_detail.transaction_line_id)
  WHERE a.transaction_type = 'Vendor Return Authorization'
      AND   a.date_last_modified >= '1900-01-01 00:00:00'
      AND   b.subsidiary_id = 27
Order by 
TRANSACTIONS.transaction_id,
TRANSACTION_LINES.transaction_line_id;
